### ISSUE TITLE
/me doesn't render correctly on mobile

### ISSUE THREAD

**Issue by swallitsch** [zulip/zulip-mobile#2786] opened 2018-07-10 18:04 UTC
![image](https://user-images.githubusercontent.com/32879218/42528357-0b8793ea-8430-11e8-9f4b-69f55db3aa4e.png)

Zulip 13.5.89
Android 8.0.0

**Comment by timabbott** [comment] 2018-07-11 04:11
/me is entirely implemented client-side in Zulip (it has to be, since it structurally changes how the message headers are displayed so you don't repeat the name of the person twice).  So the correct fix is to just extend the mobile HTML templating to handle these.  `git grep is_me_message` in the webapp is a way to see how it's implemented (there's some JS code one can borrow).

**Comment by jainkuniya** [comment] 2018-07-11 04:58
Yes this will be on client side. Will be easy to do.

@zulipbot claim

**Comment by gnprice** [comment] 2019-02-26 21:55
Duplicate of #1773 .

**Closed by gnprice** 2019-02-26 21:55 UTC
Labels: area: message list, bug, in progress
