### ISSUE TITLE
Authorization via LDAP in the mobile app Zulip

### ISSUE THREAD

**Issue by vladimirzyulyaev** [zulip/zulip-mobile#1463] opened 2017-11-27 11:14 UTC
Hello!
Please add authorization by login in your application (we use LDAP). Zulip server is installed locally.

You answer:
 Zulip 24 ноября 2017 г.
LDAP auth for the mobile app should just work (just use the password login form). If that's not working for you, can you report a bug at https://github.com/zulip/zulip-mobile/issues/new or chat with us on #mobile on chat.zulip.org so we can debug your problem? 

When entering local zulip server address in mobile application, we get authorization form including email/password, we would like it to be using cn(ldap)/password

**Comment by borisyankov** [comment] 2017-11-27 11:52
What happens if you enter the `cn` in the email field?
We should make the label not say only 'email' but I suspect it should work.

Also pinging @timabbott and @showell who know about the server-side part.

**Comment by vladimirzyulyaev** [comment] 2017-11-27 12:44
When you enter cn goes "Enter a valid email address"

**Comment by borisyankov** [comment] 2017-11-27 13:13
Oh, ooooh. Good point, this is not intentional.
We have considered the functionality, but we need to remove the validation from the field.
I was just preparing a new Beta with a subsequent Public release, so a fix for this will ship very soon.

**Comment by borisyankov** [comment] 2017-11-29 18:19
Hey Vladimir,
We just released a Beta version that fixes this issue (and I also pushed the same version to go public within few hours)
When you see version `3.3.43` available for you, give it a try and let me know if it works for you.

**Comment by vladimirzyulyaev** [comment] 2017-11-30 06:56
Awesome! I can now login using cn but there's a new problem. After login I can't see anything (users, symbols chat.) Instead, gray squares

**Comment by timabbott** [comment] 2017-11-30 07:13
@vladimirzyulyaev can you post a screenshot easily?  That sorta sounds like some sort of network error connecting to your server after login.

**Comment by vladimirzyulyaev** [comment] 2017-11-30 07:29
![1](https://user-images.githubusercontent.com/34025842/33418944-56f48df4-d5b9-11e7-9ba0-e14c88d750bf.jpg)
![2](https://user-images.githubusercontent.com/34025842/33418947-59bc554e-d5b9-11e7-97d1-6cfbd62f1437.jpg)

**Comment by borisyankov** [comment] 2017-11-30 18:15
Hey, I just published a new version to the Play Store.
I could not reproduce your particular issue, though there is some chance that we fixed this (we fixed other things though).

If the issue still persists, we should try to debug it somehow.

**Comment by vladimirzyulyaev** [comment] 2017-12-01 06:42
Unfortunately, not fixed. On the desktop version are all displayed.

**Comment by jpellman** [comment] 2018-05-02 19:43
I'm able to replicate the auth issue on version 12.4.84 of the mobile app on Android.  My Zulip host is configured to use LDAP where the username is not an e-mail address and stored within LDAP according to scenario C [here|https://github.com/zulip/zulip/blob/9a0fdf5b8dca376570bc182428ba6148fdba52c1/zproject/prod_settings_template.py#L366-L394].  When I try to log in with just the LDAP username and validation tells me that I can't because it's not an e-mail address.  Entering the e-mail address does not work to authenticate.

**Comment by timabbott** [comment] 2018-05-02 20:00
@borisyankov @gnprice the original LDAP issue should be straightforward to verify in the code: If `server_settings` returns `require_email_format_usernames=False` in the response, we should not include "email address" validation in the field and label the field appropriately as a username, not an email.

**Comment by borisyankov** [comment] 2018-05-02 20:09
@timabbott There were two other cases where we needed the `server_settings`, I am adding persistence for that setting next. Can we not get this via the `register` call?

**Comment by timabbott** [comment] 2018-05-02 20:12
This is on the login screen, and thus always before `register`.  The whole point of `server_settings` is that it's the thing you can do without any credentials.

**Comment by borisyankov** [comment] 2018-05-02 20:14
Yeah, for that call sure, we already request it there, I was considering the other cases too.

**Comment by borisyankov** [comment] 2018-05-19 13:32
We now take into account `require_email_format_usernames` and this will work with the next release.

**Closed by borisyankov** 2018-05-19 13:32 UTC
Labels: bug, in progress
