### ISSUE TITLE
openid authentification not working

### ISSUE THREAD

**Issue by matthiasrambow** [zulip/zulip-mobile#1785] opened 2018-01-24 07:19 UTC
When trying to connect to a Zulip server authenticating via an OpenID Connect service, the user is not forwarded to the service's login page. Instead just the server name and logo is shown in the the login screen. Consequently a log in to this server is impossible. In the browser and in the desktop app everything is working as expected.

**Comment by borisyankov** [comment] 2018-01-24 13:34
@timabbott @gnprice do you have any idea how this would differ from our current Google and Github login? I haven't tested anything else.

**Comment by matthiasrambow** [comment] 2018-01-24 14:05
I guess the redirect url to the identity provider must be defined somewhere in the server settings. I am no js developer, but as far as I can see, those urls seem to be hard coded in src/start/AuthScreen.js for Google and Github.

**Comment by borisyankov** [comment] 2018-01-24 14:25
Ah, I now understand your point. You are never even giving the option to login to this server. I understand why.
Would you mind giving me the address to this server (if publicly accessible)? I wouldn't need an account to test.

**Comment by matthiasrambow** [comment] 2018-01-24 15:02
@borisyankov I need to ask the the server owner first. I'll let you know.

**Comment by matthiasrambow** [comment] 2018-01-24 16:01
@borisyankov I sent you the server address via twitter.

**Comment by borisyankov** [comment] 2018-01-24 17:27
Great! Got it.

**Comment by timabbott** [comment] 2018-01-24 18:41
@borisyankov I have some context from talking to other users who are using our "Apache REMOTE_USER SSO" auth backend and are interested in getting mobile working on this front.  I don't quite understand how @matthiasrambow's auth setup works (more detail on that would help!) but I think we might need to add a little backend code to support the `mobile_flow_otp` model with other auth methods to make this work?  Not sure.

**Comment by borisyankov** [comment] 2018-01-24 19:23
@timabbott We are intercepting the return url via the `zulip://` protocol.

@matthiasrambow I connected to the server to see how the app handles this.
We do not return any entry for this in our server `authentication_methods` setting.

**Comment by matthiasrambow** [comment] 2018-01-25 07:04
Information on our specific identity provider can be found [here](https://login.mitro.dkfz.de/). But I think the solution should be generic to any OpenID Connect/OAuth2 service.

**Comment by matthiasrambow** [comment] 2018-01-25 09:42
@timabbott I just received the info from the server owner, that in the zulip/apache server settings  [libapache2-mod-auth-openidc](https://github.com/zmartzone/mod_auth_openidc) is used. 
In `etc/zulip/settings.py` `zproject.backends.ZulipRemoteUserBackend` is the only option for `AUTHENTICATION_BACKENDS` and in `/etc/zulip/zulip.conf`: 
`puppet_classes = zulip::voyager, zulip::apache_sso`
I hope that helps

**Comment by martinlablans** [comment] 2018-02-06 21:20
I can reproduce this problem and managed to narrow it down:

The Zulip mobile client calls `/api/v1/server_settings?` The server responds as follows:

```json
{
	"require_email_format_usernames": true,
	"zulip_version": "1.7.1",
	"authentication_methods": {
		"github": false,
		"dev": false,
		"ldap": false,
		"password": false,
		"google": false,
		"email": false
	},
	"realm_uri": "https:\/\/my.realm.org",
	"msg": "",
	"realm_name": "MyRealm",
	"result": "success",
	"email_auth_enabled": false,
	"realm_description": "<p>The coolest place in the universe.<\/p>",
	"realm_icon": "\/user_avatars\/2\/realm\/icon.png?version=2"
}
```

Note that `authentication_methods` are all `false` -- even though Web UI shows `RemoteUser` as enabled and `settings.py` shows

```
AUTHENTICATION_BACKENDS = (
    # 'zproject.backends.EmailAuthBackend',  # Email and password; just requires SMTP setup
    # 'zproject.backends.GoogleMobileOauth2Backend',  # Google Apps, setup below
    # 'zproject.backends.GitHubAuthBackend',  # GitHub auth, setup below
    # 'zproject.backends.ZulipLDAPAuthBackend',  # LDAP, setup below
    'zproject.backends.ZulipRemoteUserBackend',  # Local SSO, setup docs on readthedocs
)
```

Understandably, the Android client does not know what to do. The server implementing OpenID (Apache on port 8888 as intended by [Zulip's documentation](https://zulip.readthedocs.io/en/latest/prod-authentication-methods.html#remote-user-sso-authentication) is never even contacted.

This might not even be a problem with OpenID. Has anyone ever managed to get the Android client with `RemoteUser` backend?

**Comment by timabbott** [comment] 2018-02-06 22:03
The problem here is that the RemoteUserBackend doesn't support the mobile app; changes are needed server-side to allow this.  I'm going to read a bit of code to estimate the work involved, since obviously this should be supported and I'd like to see it resolved quickly.

**Comment by timabbott** [comment] 2018-02-06 22:13
I opened https://github.com/zulip/zulip/issues/8291 for the issue on the backend.

@borisyankov I suspect we'll need to make some changes to the app as well; to support that, I guess I'll plan to quickly setup a small test server using the code resolving #8291 that you can test against.  Basically, if REMOTE_USER_BACKEND is enabled (which we can add to the `/server_settings` response), we'll need to do a redirect to `/accounts/login/sso?mobile_flow_otp=<OTP>` (and otherwise the flow should work like Google and GitHub).  We still need to add the backend support for this, but I think it should be simple.

**Comment by timabbott** [comment] 2018-02-06 22:44
The answer seems to be that this is very little work.  I've opened https://github.com/zulip/zulip/pull/8294.  I'll deploy that on a fresh VM (should be a good opportunity for me to QA the new installer), setup REMOTE_USER_BACKEND, and then give @borisyankov the details so that we can verify the mobile side implementations.

**Comment by timabbott** [comment] 2018-02-24 17:13
This was just merged on the backend via https://github.com/zulip/zulip/pull/8294 and here via #1962.  

Before we close this, I want to add a note on how we could make it significantly better.

@borisyankov, for SSO login, the way it works on the backend is that it'll be the only supported auth backend for the server; as a result, probably what should happen is that when you submit the "what's your Zulip server" form, we should immediately open the webview, rather than making the user click "Login with SSO".  That's how the SSO integration works on the web for most folks using it, and so it'll both match user expectations and also save an unnecessary step.  If this is easy, we should just do it now; if not, we should make a new issue for just that enhancement when we close this.

**Comment by borisyankov** [comment] 2018-02-24 22:12
Yeah, that is exactly what I intended to do 👍 
If there is only one auth option (weather SSO or some other) the login will go directly into that step.

**Comment by borisyankov** [comment] 2018-03-03 08:50
Implemented.

**Closed by borisyankov** 2018-03-03 08:50 UTC
Labels: in progress
