### ISSUE TITLE
Black screen appears when user click on `Share` option.

### ISSUE THREAD

**Issue by nikhilmaske-2001** [zulip/zulip-mobile#4407] opened 2021-01-14 04:21 UTC
**Issue Description:**
Black screen appears when user click on `Share` option. It's a bug and it is also discussed in this [thread](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Black.20screen.20on.20share).

**How to Reproduce**

Step 1 : Open **Zulip v27.157** android app.
Step 2 : Long tap on any message.
Step 3 : Choose `Share` option.

**Screenshot** 
![Black screen](https://user-images.githubusercontent.com/59444243/104544801-b344cb00-564e-11eb-9558-70ed9ffd1ced.png)

**Comment by abhi0504** [comment] 2021-01-14 10:15
@nikhilmaske-2001 are you working on this or can I take this?

**Comment by nikhilmaske-2001** [comment] 2021-01-14 10:42
No @abhi0504 I am not working on it. You can take it.

**Comment by gnprice** [comment] 2021-01-14 21:12
Thanks for the report!

This reproduces for me on v27.158 too, the current beta release. That was on a Pixel 4 running Android 11.

It did *not* reproduce for me when I tried it just now on iOS: specifically on v27.157, on an iPhone 7 running iOS 12.4.1. Sharing is a feature that involves some platform-specific code, so it's natural that a bug like this might exist on only one platform. I've marked the issue with our "area Android" label because it looks like it's specifically on Android.

**Comment by gnprice** [comment] 2021-02-18 06:26
For cross-reference: there's some later discussion in [this chat thread](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Black.20screen.20appears.20when.20user.20click.20on.20.60Share.60.20option.2E/near/1119224).

**Comment by gnprice** [comment] 2022-03-21 22:26
The upstream issue https://github.com/expo/react-native-action-sheet/issues/203 has been closed as fixed, and we've upgraded to the version with the fix. That happened in #5203, for the v27.181 release.

I just tried the original repro recipe (thanks @nikhilmaske-2001 for a nice clear recipe!) in v27.182, the current beta, and I no longer reproduce.

So I believe this has been fixed! Thanks again @nikhilmaske-2001 for the report, and @abhi0504 for the debugging and the report upstream.

**Closed by gnprice** 2022-03-21 22:26 UTC
Labels: a-Android, a-message list, a-share-from
