### ISSUE TITLE
Feature Suggestion: Image customisation during upload flow.

### ISSUE THREAD

**Issue by ishammahajan** [zulip/zulip-mobile#3523] opened 2019-06-14 13:23 UTC
Customisation of image uploads is seen in many popular competitor apps (like WhatsApp, Instagram direct and LinkedIn). The lack of such a feature is noticeable in Zulip Mobile, if it is also extensively used by the user in other applications. 

Even though the user might be able to edit the image before sending in other applications, many image intensive workflows are aided by this feature being present in the app itself during the flow of image upload.

Leading with that, I think this is a potentially good feature to add. Listed customisations _could_ include -
- Cropping
- Adding Stickers
  - Context based stickers like time/date
  - Static stickers of certain shapes
- Adding text
- Drawing on top of the image

We should gauge these against what our users demand and selectively implement features in order to maximise output against resources.

**Comment by gnprice** [comment] 2024-10-17 05:57
Just ran across this again in our tracker, and I see now it's a duplicate of #2766.

I'll make a note there that there are some useful other details over here.

**Closed by gnprice** 2024-10-17 05:57 UTC
Labels: a-compose/send, experimental UI/UX
