### ISSUE TITLE
Empty topic field

### ISSUE THREAD

**Issue by r4mp** [zulip/zulip-mobile#3703] opened 2019-11-26 09:48 UTC
If the topic field is empty, it is still possible to click the "send"-button, which results in an infinit spinner, but without really sending the message.

**Comment by ray-kraesig** [comment] 2019-11-26 20:50
I haven't been able to reproduce this so far: for me, pressing Send when the topic field is empty results in the posted topic being the string "(no topic)".

* What version of the app are you using (under Settings → Diagnostics), and on what OS?
* Do you know what version of the Zulip server you're connecting to?
* Can you still reproduce this? (It may have been a transient connection issue.)

**Comment by chrisbobbe** [comment] 2020-01-07 02:20
This looks like it may be addressed further in https://github.com/zulip/zulip-mobile/issues/3743? @ray-kraesig

**Comment by ray-kraesig** [comment] 2020-01-08 02:15
This is, indeed, very likely a combination of #3743 and #3731, as described in the latter. (Thanks!)

Closing in favor of those, since the former has an active PR.

**Closed by ray-kraesig** 2020-01-08 02:15 UTC
