### ISSUE TITLE
reaction: Adding/removing reactions not working in message list.

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#2806] opened 2018-07-14 05:13 UTC
API is responding with status 400.

<img width="616" alt="screen shot 2018-07-14 at 10 46 02 am" src="https://user-images.githubusercontent.com/18511177/42721154-2de3d09a-8753-11e8-9f00-ec987b5bf023.png">

@zulipbot claim

**Comment by jainkuniya** [comment] 2018-07-14 05:15
It is not working on chat.zulip.org, but working on realms at `zulipchat.com`. Might be due to recent changes on server.

cc @timabbott @HarshitOnGitHub

**Comment by HarshitOnGitHub** [comment] 2018-07-14 06:29
@jainkuniya I think simply updating the mapping you have checked in mobile repo and trying again should fix this.

**Comment by timabbott** [comment] 2018-07-15 12:13
@jainkuniya a couple notes:
* It looks like your API request isn't setting `reaction_type` properly?
* If you're upvoting an existing emoji reaction, ideally you'd be just passing the same `emoji_name` and `emoji_code` that are present in the existing reaction; if you do that, this sort of error should never happen even if the server and app have different versions of the emoji data.  This is important because different people will be running different server versions at any given time.
* For our new "add the first emoji reaction" feature, we should make sure that we're using the latest emoji data, and probably should just send the emoji_name (not also the code), because will be more robust to potential version mismatches between the client app and the server about the emoji data.

**Comment by jainkuniya** [comment] 2018-07-15 12:20
Ok! Will check it out.

**Comment by gnprice** [comment] 2018-08-01 16:55
The [original report](https://chat.zulip.org/#narrow/stream/48-mobile/subject/reactions.20bug/near/612890) of this issue adds:
> Currently on mobile. I cannot add my own entry to an already existing react (such as when I want to add my own vote to a :+1: that someone made to a post)

The user was on v14.1.91 on Android.

**Comment by gnprice** [comment] 2018-08-01 17:07
FWIW, this works fine for me, on 16.0.93 (the new alpha) on Android. I'm not aware of anything recent that would have fixed this, though I'm not sure I recall everything since 14.1.91.

@jainkuniya , it sounds like you reproduced this issue -- what did you do that reproduced it?

**Comment by jainkuniya** [comment] 2018-08-04 21:08
Yup! I got the reproduction.

Problem is: we are not sending complete data to server.

>  <img width="616" alt="screen shot 2018-07-14 at 10 46 02 am" src="https://user-images.githubusercontent.com/18511177/42721154-2de3d09a-8753-11e8-9f00-ec987b5bf023.png">

For this, correct (updated) emoji name is `8_ball`. Will be fixed by #2869.

I am also getting some other issue, on upvoting an existing emoji reaction.
<img width="706" alt="screen shot 2018-08-05 at 2 36 47 am" src="https://user-images.githubusercontent.com/18511177/43680441-831fdf7a-9858-11e8-81b7-33934e5a5f4d.png">

Will fix it next 👍

**Comment by gnprice** [comment] 2018-11-09 23:36
OK, having now read #2983, this is indeed the issue that's aimed to fix. Let's consolidate discussion on the original report #2784 , and the PR.

**Closed by gnprice** 2018-11-09 23:36 UTC
Labels: in progress
