### ISSUE TITLE
Night mode toggle also switches to Home card

### ISSUE THREAD

**Issue by harshbisle** [zulip/zulip-mobile#3994] opened 2020-03-22 16:56 UTC
![20200322_222025](https://user-images.githubusercontent.com/41483548/77255174-8ec8ce00-6c8b-11ea-9a39-3ec7c1d4c42c.gif)

Like many folks I am a big fan of night mode. Sometimes I would even love to play around it but in zulip mobile when I click on on the night mode button it directly takes me to other mode and I can't immediately switch between the modes . I think it's an issue to be solved.

**Comment by jainkuniya** [comment] 2020-03-22 19:15
It is a recent regression, I remembered it was working as expected some time back. You can use `git bisect` to figure out which commit actually caused this.
My notes of `git bisect` https://jainkuniya.github.io/git-bisect-the-saviour/

**Comment by harshbisle** [comment] 2020-03-23 03:29
I will look into it thanks @jainkuniya

**Comment by ray-kraesig** [comment] 2020-03-24 23:27
Interestingly, if you move the theme toggle into the notifications card, toggling it doesn't kick you back out to the home screen; it leaves you on the notifications card. However, if you then hit Back, you're presented with the home tab, rather than the settings tab.

Currently, theme changes are handled in `src/boot/StylesProvider.js`, via the React Context API. The use of `key={theme}` there causes a re-`render()` of all visible UI components; presumably this is the point at which the "current-tab" navigation state is lost. (Removing `key={theme}` causes the theme to mostly not be applied.)

It's plausible that what we really want to do here is to eliminate the ThemeContext in favor of just keeping the theme state in the Redux store, like everything else, and keeping watch on it from there.

**Comment by gnprice** [comment] 2020-03-30 21:27
> (Removing `key={theme}` causes the theme to mostly not be applied.)

I think this is because in many places we still use React's legacy context API. As its docs say:
https://reactjs.org/docs/legacy-context.html#updating-context

> Updating Context
>
> Don’t do it.
>
> React has an API to update context, but it is fundamentally broken and you should not use it.

So the `key={theme}` is our workaround, for causing updates even while the (legacy) context API doesn't.

In new code, or where we're substantially changing the logic that consumes the theme anyway, we've generally moved to React 16's new context API. That one properly causes updates:
https://reactjs.org/docs/context.html#contextprovider

> All consumers that are descendants of a Provider will re-render whenever the Provider’s `value` prop changes.

Whatever we do, we should move off the legacy context API before too long; in addition to this problem, it'll be dropped in a future post-16.x release of React.

Migrating is #1946. See in particular https://github.com/zulip/zulip-mobile/issues/1946#issuecomment-579570887 , the commit linked there, and the later commit a606bf304 for more details and examples of the migration.

> It's plausible that what we really want to do here is to eliminate the ThemeContext in favor of just keeping the theme state in the Redux store, like everything else, and keeping watch on it from there.

Yeah, this is also plausible. I think the bulk of the work involved in #1946 , migrating from the old to the new context API, will be work we'll also need for that -- because it's mostly about disentangling the theme from the rest of our shared `styles` objects. So I think a good strategy would be to pick up #1946 and complete that (it's just under half done now). Then potentially we might follow up by migrating all the theme references together, from the new context API to Redux.

**Comment by agrawal-d** [comment] 2020-06-15 17:23
I always used to think this was by design :)

**Comment by gnprice** [comment] 2020-06-16 00:39
Yeah, it's a bug :)

It looks like this isn't already explicit on this thread, so to be clear: it's a very low-priority bug. This is something most users will do either zero or one times ever, unless they're one of us actively doing development on the app; and then when they do, the impact is a bit jarring but harmless.

**Comment by kelvinngure** [comment] 2020-07-13 03:01
I just started using your app and this was the first thing I noticed since when I use a new app, the first thing I do is switch to night mode. It's quite noticeable

**Comment by chrisbobbe** [comment] 2020-07-13 16:48
https://github.com/zulip/zulip-mobile/pull/4046 would fix this; @gnprice has already reviewed and merged several of its commits, but there are a few more. 🙂

**Comment by chrisbobbe** [comment] 2020-07-20 19:18
> We may get more attention to this issue

We've had another report of this, at https://github.com/zulip/zulip-mobile/issues/4197. I think my PR isn't unusually complicated, and hopefully it's easier to review now that I've swept away some distracting conversations by opening #4199. 🙂

**Closed** 2020-07-31 01:03 UTC
