### ISSUE TITLE
Korean characters replaced with underscores in downloaded filenames

### ISSUE THREAD

**Issue by pjb7687** [zulip/zulip-mobile#5884] opened 2024-08-28 23:24 UTC
When downloading files with Korean characters in the filename, the Korean characters are replaced with underscore (_) characters. This issue might also extend to other CJK (Chinese, Japanese) characters as well.

**Steps to reproduce:**
- Upload a file with Korean characters in the filename (e.g., "한글_파일.txt")
- Attempt to download the file
- Observe that the downloaded filename replaces Korean characters with underscores (e.g., "______.txt")

**Expected Behavior:**
- The downloaded file should retain its original filename with Korean (and other CJK) characters intact.

I am using Zulip server 9.1 (self-hosted via Docker compose). This happens on the latest Zulip clients across various OS, including Windows, Linux, and Android, so I guess this is a server issue.

**Zulip Server and web app version:**

- [ ] Zulip Cloud (`*.zulipchat.com`)
- [x] Zulip Server 9.x
- [ ] Zulip Server 8.x
- [ ] Zulip Server 7.x
- [ ] Zulip Server 6.x or older
- [ ] Other or not sure

**Comment by chrisbobbe** [comment] 2024-08-30 21:51
Ah thanks @andersk for transferring this. I'll mark this as a duplicate of #5884 which has our current diagnosis and planned fix.

**Closed by chrisbobbe** 2024-08-30 21:51 UTC
Labels: bug, duplicate
