### ISSUE TITLE
Can't upload video from camera roll

### ISSUE THREAD

**Issue by maltokyo** [zulip/zulip-mobile#3624] opened 2019-09-20 12:36 UTC
Only can upload photos.  Can't upload any videos or other filetypes.
(even in the beta version, which I tried also)

[edit: this report was on iOS; edited title based on follow-up report in later comment.]

[edit: see [below](https://github.com/zulip/zulip-mobile/issues/3624#issuecomment-885781394) for a proposed solution that should hopefully be pretty easy?]

**Comment by astyltsvig** [comment] 2020-01-14 09:31
I cant either do that from android

**Comment by gnprice** [comment] 2020-01-21 21:00
Hi! Thanks for the reports.

I just tested, and this works for me. (On Android 10 with v26.20.143, the latest.) @maltokyo @astyltsvig can you say in more detail what steps you try, and what result you see?

One thing that may confound this is #2684. Videos tend to be much bigger than photos, so they can naturally take some time to upload (often like 10 seconds, potentially much longer), depending on the speed of your connection to the Internet and to your Zulip server. We ought to show something like a progress bar while that's happening, but we currently don't and instead it looks like nothing happened at all, until the whole file finishes uploading; that's #2684.

**Comment by chrisbobbe** [comment] 2020-01-23 02:20
Hmm; I wasn't aware that attaching video from the camera roll is supported. Maybe it's Android-only, @gnprice ? It sounds like https://github.com/zulip/zulip-mobile/issues/2939 should be updated.

**Comment by gnprice** [comment] 2020-04-25 03:30
I just reproduced this on iOS -- specifically on an iPhone XR running iOS 13.3 and Zulip 26.27.150.
* I went and recorded a short video from the camera app.
* Then went to Zulip, opened a conversation, and hit the "plus" icon and the "image" icon, to select something to upload from the camera roll.
* The UI showed me all the photos in the camera roll, but not the video I'd just taken.

This looks like we're just not using the right API on iOS to say "please let the user select a photo *or video* from the camera roll" -- we're probably instead invoking the API in a way that says "please let the user select *specifically a photo* from the camera roll".

The relevant code in our app is in `src/compose/ComposeMenu.js`, specifically in `handleImagePicker`. It looks like this:
```js
import * as ImagePicker from 'react-native-image-picker';
// ...

  handleImagePicker = () => {
    ImagePicker.launchImageLibrary(
      {
        quality: 1.0,
        noData: true,
        storageOptions: {
          skipBackup: true,
          path: 'images',
        },
      },
      this.handleImagePickerResponse,
    );
  };
```

So the fix might be as simple as changing those options we pass to that `launchImageLibrary` function from `react-native-image-picker`. In particular, from a quick look at [its API docs](https://github.com/react-native-community/react-native-image-picker/blob/master/docs/Reference.md), we should likely be passing `mediaType: 'mixed'`.

The next steps for someone to try to resolve this would be to
* reproduce the issue in a development version on iOS
* try adding that option and see if it works
* if so, test that things still work right on Android too after that change.

**Comment by gnprice** [comment] 2020-04-25 03:33
We also just had [another report](https://chat.zulip.org/#narrow/stream/48-mobile/topic/general.20features/near/862490) that this didn't work on Android, with an interesting detail:
> About attaching videos actually even here on android I only see images listed when we use send image option, we use the send file option to send videos

Maybe "send file" is what I used when I tried this earlier (https://github.com/zulip/zulip-mobile/issues/3624#issuecomment-576879342) on Android and it worked for me? If so then that actually makes more sense -- I'd hope for this `react-native-image-picker` library to have the same behavior in this respect on Android vs. iOS.

Anyway, the steps I posted just above still apply, except you can probably try either Android or iOS first before testing the change on the other. Either way, be sure to test you can reproduce the issue before adding a fix :slightly_smiling_face:

**Comment by ray-kraesig** [comment] 2020-04-29 21:22
Unfortunately, `mediaType: 'mixed'` is not available on Android until `react-native-image-picker` v2.0.0; prior to that, only `'photo'` and `'video'` were available options on Android. ([v1.1.0 docs](https://github.com/react-native-community/react-native-image-picker/blob/v1.1.0/docs/Reference.md#options).)

Fortunately, using it anyway it doesn't break anything – I've just tested `mediaType: 'mixed'` on Android for both sending an image (`IconImage`) and taking a picture (`IconCamera`) on Android, and there was no change in behavior. (That is, only images could be selected or sent.)

**Comment by chrisbobbe** [comment] 2021-07-23 17:13
> until `react-native-image-picker` v2.0.0

We're now on 2.3.4 (with plans to upgrade further). Looks like the current `main` branch shows support for `mediaType: 'mixed'` on both iOS and Android, so I'd expect a fix to be pretty simple: https://github.com/react-native-image-picker/react-native-image-picker#options

**Comment by chrisbobbe** [comment] 2021-12-03 02:05
> I'd expect a fix to be pretty simple

There's a small problem: on the current latest react-native-image-picker (4.3.0), the response from the image picker doesn't include `fileName` for videos, so our code fails. The fix should be pretty simple, and I've sent a PR: https://github.com/react-native-image-picker/react-native-image-picker/pull/1880 . With that change, it works as I'd expect with `mediaType: 'mixed'`, on iOS. (Haven't tested on Android yet.)

**Comment by chrisbobbe** [comment] 2021-12-04 02:28
> I'd expect a fix to be pretty simple

I've just filed https://github.com/react-native-image-picker/react-native-image-picker/pull/1881 for another issue, then maybe it'll be simple? 🤞

**Comment by Komal7209** [comment] 2022-04-14 00:44
@chrisbobbe Is this issue assigned to someone else or still open to work because as per above conversation , I'm unable to get that is it resolved or not?

**Comment by chrisbobbe** [comment] 2022-04-14 01:36
This issue has gotten stalled waiting for an upstream PR (current status [here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/react-native-image-picker/near/1298262)); I'd recommend choosing a different issue to work on.

**Comment by Komal7209** [comment] 2022-04-14 01:42
@chrisbobbe I can see that all good first issues have been taken by one or other person so is there some other issue on which I could work so that I could start with contribution and also get somehow familiarised with that portion of code. If you could suggest some other tag of issues in which I could search

**Comment by alya** [comment] 2022-04-14 05:52
@Komal7209 please see https://zulip.readthedocs.io/en/latest/overview/contributing.html#picking-an-issue-to-work-on. I highly recommend reading through that entire page as you're getting started. Thanks!

**Comment by gnprice** [comment] 2022-09-27 21:27
Another user request for this recently:
https://chat.zulip.org/#narrow/stream/48-mobile/topic/.233624.20video.20upload/near/1436542

**Comment by RealHarshAgarwal1** [comment] 2022-09-30 12:48
Hey everyone I'm new to open-source can anyone guide me on how I can get started I just searched good first issue and got here I also forked zulip mobile repo

**Comment by alya** [comment] 2022-10-01 05:38
Welcome @RealHarshAgarwal1 ! Please go through the [Zulip contributor guide](https://zulip.readthedocs.io/en/latest/contributing/contributing.html), as well as the mobile-specific instructions at https://github.com/zulip/zulip-mobile#contributing.

**Comment by marshallmassengill** [comment] 2022-12-14 14:38
Any update on this that can be provided?  This is a major issue for us in adopting Zulip at the moment.  Are there any workarounds via plugins for uploading videos?

**Comment by chrisbobbe** [comment] 2023-07-17 20:30
We've had another request for this: https://chat.zulip.org/#narrow/stream/48-mobile/topic/iOS.20issues/near/1611128

**Closed** 2023-08-18 00:34 UTC
Labels: a-compose/send
