### ISSUE TITLE
Unsendable messages have frozen spinners

### ISSUE THREAD

**Issue by ray-kraesig** [zulip/zulip-mobile#3730] opened 2019-12-18 00:39 UTC
Unsendable messages appear in the message list with a frozen spinner, as shown below.

![Screenshot_20191217_163124](https://user-images.githubusercontent.com/54861490/71045688-c2bfb080-20ea-11ea-959f-301a0343cd4b.png)

(This is a reprise, but apparently not a duplicate, of #1546.)

**Comment by ray-kraesig** [comment] 2019-12-20 19:11
This is fine in a modern Webview; [per MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/animation#Browser_compatibility) it should only fail on Chrome <43, where the `animation` property isn't supported.

On the other hand, the `-webkit-animation` property *is* supported as early as Chrome 18.

**Comment by gnprice** [comment] 2019-12-31 06:53
Huh, is this limited to unsendable messages? Or does it apply to all messages -- so e.g. if you're offline or have a slow connection, just enough to observe the spinner for more than a moment, you see the same effect?

I see also #3731 which is about "permanently unsendable" messages; is that the same set of messages?

**Comment by gnprice** [comment] 2019-12-31 07:08
Ah I see, but also this is only on Chrome <43. Copying what I just wrote on the PR #3735 (maybe I should have made the detailed comment here in the first place; oh well):

---
Hmm, this is quite a fair bit of duplication: 23 lines across 8 places in the file. [Which is a perfectly reasonable way of making the fix; it's just the nature of the fix.]

Here's what we say (in `js.js`) about old Chrome versions:

```
 * * For Android, core functionality needs to work on Chrome 44.
 *   Graceful degradation is acceptable below Chrome 58. [...]
 *
 *   * Below Chrome 44, it's possible (but rare) for a user to be on a
 *     version as old as Chrome 37, which shipped with Android 5 Lollipop.
 *     We sometimes fix issues affecting those versions, only when trivial.
```

I think the complexity of this fix falls well above the "trivial" threshold, in terms of its maintenance cost for ongoing changes to our CSS styles.

Happily the issue is also fairly minor: it doesn't affect the actual functionality, and most users will rarely to never see it at all. So I think it's the kind of "graceful degradation" I'd be OK with at any Chrome version below 58, when the fix isn't trivial.

Thanks for looking into this! I think based on the information collected, the best path is to close the PR and issue (as WONTFIX), and turn attention to other bugs and features.

**Closed by gnprice** 2019-12-31 07:08 UTC
Labels: a-compose/send, a-message list
