### ISSUE TITLE
message list: Show users associated with reactions.

### ISSUE THREAD

**Issue by jackrzhang** [zulip/zulip-mobile#3092] opened 2018-10-31 05:58 UTC
This is a feature request! (for the longer term)

On the web application, users can see the users associated with a reaction via text that appears after hovering over the reaction.

On Slack's mobile application, a list of users associated with reactions to a message slides up from the bottom of the screen after a long press on one of the reactions to the message.

(@zulipbot label "area: message list")

**Comment by jainkuniya** [comment] 2018-10-31 06:13
(#2252)

**Comment by timabbott** [comment] 2018-10-31 16:36
Yeah, I'd really love to see this too; it's one of the few places where the mobile app just doesn't offer you information you might need to interpret message content.

**Comment by jainkuniya** [comment] 2018-10-31 16:46
(on it)

**Comment by gnprice** [comment] 2018-11-07 03:03
Closing as a duplicate of #2252 .

**Closed by gnprice** 2018-11-07 03:03 UTC
