### ISSUE TITLE
MessageReactionsScreen: Overlapping of emojis tabs 

### ISSUE THREAD

**Issue by rajprakash00** [zulip/zulip-mobile#4508] opened 2021-03-04 07:25 UTC
Currently if we have a bunch of emoji reactions on a message and then on visiting **See who reacted** screen
 we can see the emoji tabs are overlapping upon each other thereby making it difficult to view reaction count no. & 
giving a weird view for any user.

**Screenshots/Media**:

https://user-images.githubusercontent.com/42652941/109925782-2cc07780-7ce8-11eb-952a-604171ed77c2.mp4

**Additional Context**:

Working on a PR for this

**Comment by chrisbobbe** [comment] 2021-04-05 21:09
Thanks, @rajprakash00! Yeah; I agree this is annoying. I'm closing this as a duplicate of #3798, though, which has gathered more design discussion about what to do about it. Please let me know if I've misunderstood the symptom here, though. 🙂

**Closed by chrisbobbe** 2021-04-05 21:09 UTC
