### ISSUE TITLE
Add support for live-updating message editing that changes streams

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#4025] opened 2020-04-07 21:30 UTC
The server commits 843345dfee9c2e110e7add443f8dd3f9f6a8ace4 and 7990676583b5094e1a12572a782ece7ed57b401e (as part of #13912 / #6427) added support in the Zulip server and webapp for a new variant of the `update_message` event type, with a `new_stream_id` field.  It should work the same as the existing support for changing a topic (including the `message_ids` field with additional messages to move), except that the stream changed as well.  

I imagine these will be relatively rare, but it also didn't end up being a huge amount of work to support this in the webapp's event handling.  

Like with the webapp, the part of updating unread count data structures is likely the most important thing here.

**Comment by ray-kraesig** [comment] 2020-04-09 19:23
Is this a duplicate of #3957?

**Closed** 2020-04-09 20:40 UTC
Labels: api migrations
