### ISSUE TITLE
jump to most recent message

### ISSUE THREAD

**Issue by probabilistic** [zulip/zulip-mobile#2759] opened 2018-07-05 12:15 UTC
Regarding the iOS app. Is there any way to make it jump to the most recent message? I know there is the little arrow at the bottom, but that only jumps to the most recent message that is loaded -- which is a problem if you're like me and only use the app once every few weeks or so.

**Comment by chrisbobbe** [comment] 2020-02-25 00:37
Hi @probabilistic, thanks for your question. I'm sorry to say this is an issue we're aware of, but a fix hasn't landed yet. To focus conversation and progress on it, I'm closing this as a duplicate of https://github.com/zulip/zulip-mobile/issues/1974.

**Closed by chrisbobbe** 2020-02-25 00:37 UTC
