### ISSUE TITLE
Message list loads forever, except when very few messages

### ISSUE THREAD

**Issue by pohutukawa** [zulip/zulip-mobile#4156] opened 2020-06-15 01:55 UTC
Unless visiting a stream with only **very few** (up to about a hand-full) messages, the mobile UI never loads the topic/message list. It remains in the stylised "message list loading" type of screen (fancy spinner). To me, this seems possibly related to #4033, but it may be different (more severe?).

In our environment pretty much all users experience this on the mobile Zulip client on both Android as well as iOS. The web and desktop clients all work fully as expected, with a very responsive UI.

Side note: After an issue with the RabbitMQ queue handling on the server (issue https://github.com/zulip/zulip/issues/14862) at the time we have resolved to upgrading the server to the current Git master (beginning of May).

**Comment by gnprice** [comment] 2020-06-16 00:31
Thanks @pohutukawa for the report! That is a pretty bad experience.

One thing reported on #4033 was this workaround:

> Restarting the app (force quit and reload) fixes it immediately 100% of the time

Does that fix it for you? That's still a bad experience -- maybe *less* terrible but still bad -- but it's potentially an informative clue for us in debugging it.

**Comment by pohutukawa** [comment] 2020-06-16 01:56
Thanks @gnprice for taking this on. Yes, I have tried the force quit & reload, but it didn't work.

I've also deleted all the cache & data of the app and re-connected to our Zulip server: Same thing, nothing loads.

If I can help with gathering insights, I'm happy to provide them to my means of ability.

**Comment by pohutukawa** [comment] 2020-06-21 20:41
@gnprice any further input on this? Anything we can do to provide further data to debug the problem?

**Comment by chrisbobbe** [comment] 2020-06-24 05:23
The loading view you're seeing is this one, right; gray squares and lines covering most of the screen?

![image](https://user-images.githubusercontent.com/22248748/85504072-12060280-b5a0-11ea-8a72-77c7aa5bb8a1.png)

Or is it a circular spinner?

**Comment by pohutukawa** [comment] 2020-06-24 21:08
@chrisbobbe Yes, it's the "stripey one" in the screen shot above.

**Comment by pohutukawa** [comment] 2020-06-30 22:47
Ping.
Any help I can provide for further insights on debugging. For quite a while the mobile Zulip client is completely unusable, now. People are starting to scream to go back to Slack again, which I'd like to avoid.

**Comment by gnprice** [comment] 2020-07-01 03:17
@pohutukawa Thanks for your persistence with this!

I think in order to get helpful logs for debugging this, we'll need to add some new code. I hope to have a beta version out soon with some code for that. If you haven't already, one step you can take now is to join the beta:
https://github.com/zulip/zulip-mobile/#using-the-beta
(Right now that has the same version as we've released for everyone, but it'll get each new version sooner.)

A few other ideas that might turn up an interesting clue:
* Would you make an account on our community server chat.zulip.org, and try connecting to that from the mobile app?
  * That'll help confirm whether the relevant variable that's triggering this bug is something about your Zulip server, vs. something about your network or some other variable common to you and your colleagues.
* Can you think of anything unusual about either the configuration of your Zulip server, or the way you've been using it? Perfectly fine if not; but if you can, that could potentially give a lead on a way to reproduce the issue.

**Comment by chrisbobbe** [comment] 2020-07-03 01:21
Here's an issue we haven't thought about in a while, but that's still open and a symptom is the gray bars showing indefinitely: https://github.com/zulip/zulip-mobile/issues/3281

IIUC, the theory there is that we fail silently and aren't retrying at all, and this particularly affects people with weak Internet connections.

@pohutukawa Is there anything consistent among you and your colleagues about your Internet connections, e.g., everyone's always on cellular data? (We should definitely fix this for users at all Internet speeds, but it might be a helpful debugging clue.)

**Comment by pohutukawa** [comment] 2020-07-03 05:09
@gnprice:
> A few other ideas that might turn up an interesting clue:
> 
>     * Would you make an account on our community server chat.zulip.org, and try connecting to that from the mobile app?
>       
>       * That'll help confirm whether the relevant variable that's triggering this bug is something about your Zulip server, vs. something about your network or some other variable common to you and your colleagues.

OK, I have just tried to connect to `chat.zulip.org` using my mobile client, and everything seems to work fine. Thus I'd expect that it might be an issue with an assumption on something the mobile client does from (our version of) the server vs. what the web/desktop clients do.

>     * Can you think of anything unusual about either the configuration of your Zulip server, or the way you've been using it? Perfectly fine if not; but if you can, that could potentially give a lead on a way to reproduce the issue.

If you look at my original entry in here, I did at one point upgrade our server to Git master due to a problem with the RabbitMQ queues getting the server repeatedly overloaded and stuck. So we're not quite in sync with published releases, even though on desktop/web clients everything works as expected.

@chrisbobbe:
We're here on a very reliable work WiFi network during working hours. And the problem persists no matter what network (mobile, company WiFi, home WiFi) we're on. And that's accross all Android and iOS users.

**Comment by pohutukawa** [comment] 2020-07-03 05:11
> Oh, here's another idea: Do the affected streams all seem to have large files (e.g., images) in them?

Likely. Screen shots are *very* commonly used (unfortunately even where a text copy/paste would suffice). So I'd imagine the answer to your question is "yes likely".

**Comment by gnprice** [comment] 2020-07-07 01:24
> OK, I have just tried to connect to `chat.zulip.org` using my mobile client, and everything seems to work fine. Thus I'd expect that it might be an issue with an assumption on something the mobile client does from (our version of) the server vs. what the web/desktop clients do.
> 
> [...] And the problem persists no matter what network (mobile, company WiFi, home WiFi) we're on. And that's accross all Android and iOS users.

@pohutukawa Thanks. I have the same inference from that as you do -- it seems like the variable that triggers this bug is clearly something about your server, or perhaps about the data on it.

Meanwhile, today I sent a new release to beta which adds some logging that should help us debug this: version 26.30.153. Please try out the beta:
https://github.com/zulip/zulip-mobile/#using-the-beta
and check that you get the new version, and then play around some to exercise this issue. (On Android you should get the new version immediately; on iOS there's always some lag, but if all goes well with Apple it should be available in the next 12-24 hours.)

**Comment by pohutukawa** [comment] 2020-07-07 02:34
@gnprice Thanks for that. Just joined the beta and installed the new version (Android, 26.30.153). I have force killed and started the mobile Zulip client to make sure the new version is running. So far the behaviour is still identical (getting the "stripey" wait UI while loading without a change).

If you'll let me know on how to access such logs to track down things further, I'd be glad to exercise this.

Cheers for the assistance!

**Comment by pohutukawa** [comment] 2020-07-08 21:11
What is this sentry stuff up there? I don't seem to have any credentials to do anything with the links.

**Comment by chrisbobbe** [comment] 2020-07-08 22:20
We use Sentry for logging issues encountered in the app. Greg and I have access, and we've been debugging [here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.23M4156.20Message.20List.20placeholders/near/928307). 🙂 

One thing we've noticed is that there's something odd in the shape of the data representing reactions to messages, in the response your server gives to [`GET /messages`](https://zulipchat.com/api/get-messages).

Do you know the Git commit ID of the server that's been running? There was a bug in handling that data, which was introduced in https://github.com/zulip/zulip/commit/2a4c62a326c8213331c1775c6e2fc826d9dbb2ef (committed May 19), and fixed in https://github.com/zulip/zulip/commit/a53daa6f8c7cb06ea4119a3e7c4063a47e2e7c41 (committed May 21).

You did say, at https://github.com/zulip/zulip-mobile/issues/4156#issue-638484730, that you upgraded the server in the beginning of May, though, hmm.

**Comment by gnprice** [comment] 2020-07-09 01:50
@pohutukawa We've done a bit more debugging, and I'm now pretty confident that that server bug is the one you're running into here.

I recommend you upgrade the server to a current version. There's now [a release candidate](https://zulip.readthedocs.io/en/latest/overview/changelog.html#rc1-july-1-2020) for Zulip Server 3.0, which perhaps has a somewhat reduced risk of having a really obnoxious bug like the one you unfortunately ran into with the version from Git you're currently using.

Thanks again for your persistence in reporting and helping debug this issue. I think there are some things we can change that will make the effects of an issue like this one less painful in the future, and we plan to make those changes.

**Comment by pohutukawa** [comment] 2020-07-09 04:09
I've just followed your `curl` command mentioned in the other issue thread, and this is the version I'm currently on:

```
"zulip_version": "2.2-dev-2329-g0af2f9d838"
```

I'll upgrade to the 3.0 RC next week and see how it goes.

Cheers!

**Comment by gnprice** [comment] 2020-07-09 05:12
> ```
> "zulip_version": "2.2-dev-2329-g0af2f9d838"
> ```

OK, and that commit is indeed in the range @chrisbobbe identified at https://github.com/zulip/zulip-mobile/issues/4156#issuecomment-655787636 between when that server bug was introduced and fixed! So your server is indeed currently affected by that bug. When the bug was live on our development server chat.zulip.org, it [was observed to cause](https://chat.zulip.org/#narrow/stream/2-general/topic/Reaction.20user.20data/near/882827) these same symptoms.

Closing this issue now because I believe we've completed debugging the issue, and the code is fixed in master. As I mentioned above, there are things we can change that will mitigate future issues like this one, and I've filed #4186 for the biggest of those. Do let us know how the upgrade goes, and if you run into new problems please let us know about those too.

**Closed by gnprice** 2020-07-09 05:12 UTC
Labels: P1 high-priority, a-message list

**Comment by pohutukawa** [comment] 2020-07-22 05:23
Just to confirm: Upgraded to the 3.0 version, and things are working again.

Having said that, there was an issue where I had to do a Git upgrade to the 3.0 tag, as the "latest" tar-ball would lead to an error in the upgrade. There is also another issue as I wasn't able to use the data export before the upgrade or the `stream_stats` operation. But I'll create another ticket for that.

Awesome @gnprice, much appreciated and thanks for an awesome open source software experience!

**Comment by gnprice** [comment] 2020-07-23 06:21
Excellent. Thanks @pohutukawa for confirming, and for being an awesome bug reporter!

Please do file that upgrade issue too (in zulip/zulip) -- we'll probably do a 3.1 release within the next couple of weeks, and this sort of upgrade issue is the perfect kind of thing to fix for that release.
