### ISSUE TITLE
"Mark x unread messages as read" message count is rendered incorrectly

### ISSUE THREAD

**Issue by DanWaLes** [zulip/zulip-mobile#5670] opened 2023-03-03 15:11 UTC
the number of unread messages in a stream isn't correctly rendered on iPhone 5s iOS 12.5.6 Zulip version 27.201. It was introduced sometime last month when i manually installed an update. the button works but the text is incorrect. Updating to iOS 12.5.7 didnt fix.

https://i.postimg.cc/XN1rgRg8/unread-message-count.jpg

to reproduce
1) connect to internet (if not connected already)
2) open Zuilp app
3) click on a stream with unread messages

text of some sort of language feature not working is shown, the button doesnt fit on screen (but is still functional) and the number of unread messages is not displayed

**Comment by chrisbobbe** [comment] 2023-03-03 19:07
Hmm, thanks for the report! I'm curious, if you go to the in-app settings, what language is selected for the UI? The app is translated into many languages (though incompletely, and we fall back to English where translations are missing), and I wonder if something has gone wrong with a translation.

**Comment by DanWaLes** [comment] 2023-03-03 19:22
language is set as English, i've never changed it. would switching to english uk do a difference? i'm from uk anyway

**Comment by gnprice** [comment] 2023-03-03 20:44
Thanks for the report. I believe the problem here is, unfortunately, caused by your iOS version not providing some features we rely on. We recently dropped support for iOS versions older than iOS 14, and we're now using platform features that make it possible to accurately handle plurals for translated text.

Given that we dropped support for your version of iOS, it shouldn't have been possible for you to take the upgrade to Zulip — your device should have remained at the last Zulip version that supported it. It looks like we left something out when updating the metadata that would tell your device and the App Store that the new version shouldn't be installed on your version. I'll file an issue for that and we'll follow up.

**Comment by chrisbobbe** [comment] 2023-03-03 21:00
> we're now using platform features that make it possible to accurately handle plurals for translated text.

Interesting. I noticed the iOS 12 when I read this report but couldn't think of what would break with this symptom. Do you recall what those platform features were?

**Comment by gnprice** [comment] 2023-03-03 21:25
On iOS, we use the system's JavaScript implementation (because Apple doesn't allow others), and I'm guessing that this fancy plurals feature is making use of something provided by the JS implementation.

**Comment by chrisbobbe** [comment] 2023-03-03 21:31
Indeed, `Intl.PluralRules` would be unavailable before iOS 13, I think: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules

I think the fact that 35129e50e (our first use of the fancy plurals feature) came after 783e56b23 (requiring iOS 14+) was basically a lucky accident (modulo #5672). I don't recall considering platform support as a factor in changing the value of a Format.JS message.

**Comment by DanWaLes** [comment] 2023-03-03 21:45
normally apps which aren't compatible with my device will get a message saying that they require a higher version of iOS to update or be installed. installing updates for Zulip does not have that message.
how much features require > iOS 12? if it's just the button text i'd suggest fixing it. if it's anything more then the app store should prevent the updates and installation from being possible.
Apple still gives updates to iPhone 5s. they dropped iPhone 5 a while back

**Comment by gnprice** [comment] 2023-03-04 00:21
> normally apps which aren't compatible with my device will get a message saying that they require a higher version of iOS to update or be installed. installing updates for Zulip does not have that message.

Yes. That is our mistake, as I mentioned above: it's #5672.


> how much features require > iOS 12? if it's just the button text i'd suggest fixing it.

It's this and several other places where we show some text in the UI that involves a number. Older versions of the app would show one form of text when the number was 1 and another when it was more than 1 (like "1 unread message" and "<N> unread messages"). But this makes it impossible to translate accurately for many languages — for example in some languages, the noun should look the same for 11 and 21 and 101 and so on as it does for 1.

(A bit like how in English, when the number is an ordinal, one uses "th" for 4, 5, 6, and so on, but then when the number reaches 21 one repeats the "st/nd/rd" pattern: 21st, 22nd, 23rd, just like 1st, 2nd, 3rd.)

It's possible there may be other features too. We don't have the resources to test the app on very old versions of iOS, so when things break there we don't necessarily find out.


> Apple still gives updates to iPhone 5s. they dropped iPhone 5 a while back

Yeah, they're continuing to provide bugfix and security updates for it, by continuing the iOS 12.x series. That's great, and I wish more phone vendors would do so for as long a period as Apple does. But they're no longer providing new major versions, which means you don't get the new functionality of iOS 13 and later.

**Comment by DanWaLes** [comment] 2023-03-04 00:37
so will i be left with a button with incorrect text forever, seeing as the direction is to only support iOS 14+?

**Comment by gnprice** [comment] 2023-03-04 02:01
I think we'll make one last release for iOS 12+ that just rolls back these pieces of text, so that devices on iOS 12 and 13 can go back to something that works for them.

Then future releases will be iOS 14+ and will have the text that works for more languages.

**Comment by DanWaLes** [comment] 2023-03-04 11:07
Thanks

**Comment by chrisbobbe** [comment] 2023-03-14 21:35
This was fixed in https://github.com/zulip/zulip-mobile/commit/f838a35f98d175491257eca650973511159f37a8, released in [v27.202](https://github.com/zulip/zulip-mobile/releases/tag/v27.202).

@DanWaLes, please update to v27.202; you should find that the message is English instead of nonsense, and that it tells you how many unreads there are. 🙂

Closing as fixed, but if there's an issue with the fix, please let us know and we can reopen.

**Closed by chrisbobbe** 2023-03-14 21:35 UTC
