### ISSUE TITLE
Stuck at initial loading spinner

### ISSUE THREAD

**Issue by alreadydone** [zulip/zulip-mobile#4159] opened 2020-06-15 16:09 UTC
Since yesterday, when trying to start Zulip on my Android, the "Z" wheel keeps spinning and the messages never show up. I have tried to clear cache and update, but wouldn't like to uninstall/reinstall or clear all local data, since my server list / login info would be lost. Any idea/suggestions? Thanks for your attention.

**Comment by agrawal-d** [comment] 2020-06-15 17:15
A release was made available to all users on 13 July. Perhaps this is due to the update. Do you recall updating the app recently?

If you use Play Store, you can see recently updated apps:
From the Play Store home screen, tap the Menu icon Menu (upper-left). Tap My apps & games. Then tap 'Installed'.

**Comment by alreadydone** [comment] 2020-06-15 18:05
Sorry? Today is June 15 and the latest release seems to be made on May 6 https://github.com/zulip/zulip-mobile/releases/tag/26.28.151. I first experienced the problem with an unknown earlier version, and just updated to the latest version on Google Play Store (which also shows May 6), and it doesn't help.

**Comment by agrawal-d** [comment] 2020-06-15 18:39
Hmm. I was basing my comment on this [message](https://chat.zulip.org/#narrow/stream/48-mobile/topic/release/near/903383). From that, I understood that Greg released the app on GitHub much earlier, and then to the respective stores on 13th. I'm not sure. @gnprice?

**Comment by gnprice** [comment] 2020-06-16 00:46
@alreadydone Thanks for the report! That sounds like a nasty symptom -- sorry you're running into it.

What version of the app are you using? You can see this in the Play Store (tap the arrow next to "What's new", scroll down to "App info", and look at the "Version" item), or in the app (go to settings -> Diagnostics, and it's at the top.)

The observations above are all consistent with having just updated to 26.28.151. It's dated May 6 because that's when the release was created, but then it was in beta for a while until June 13.

**Comment by alreadydone** [comment] 2020-06-16 02:30
@gnprice The version currently on my device is indeed 26.28.151, but I only updated to this version after I've experienced the problem, so the problem should already exist in an earlier version (I don't remember the old version number and don't know how to find out; I probably haven't updated for a few months).

**Comment by gnprice** [comment] 2020-06-17 19:24
@alreadydone That's helpful, thanks.

One thing that's going on here and which we should certainly improve is:
* When you launch the app, we go straight to loading current data from the last server you were using. So far that's good -- most people most of the time will want to use the same server they used last, and this helps make the experience good for that case.
* Once that data loads, we show the whole app UI, including the place to go switch to a different account/server.
* If on the other hand that attempted load is outright rejected by the server, e.g. saying your login is invalid, then we take you to the screen where you can choose a different account/server, or log in anew on that one.
* But if the load neither succeeds, nor gets a proper rejection from the server, but just hangs for a long time... then we just stay in limbo at the loading screen. :-/ This is very likely the cause of what you're seeing.

So we should fix that.

I'm also curious to try to potentially debug why the app stopped being able to load your data from the server in the first place. Do you have any ideas about what might have changed when this started happening? On the server you'd used last before seeing this problem (which is the server the app will be trying to load from), did you make any changes around that time? Is it a server you or someone else runs independently, or is it on zulip.com / zulipchat.com?

**Comment by chrisbobbe** [comment] 2020-06-17 22:48
Another possible reason for getting stock on the loading screen is that the initial fetch doesn't even start. The completion of the fetch is one trigger for navigating away from the loading screen.

`doInitialFetch` has one call site: in the `componentDidUpdate` method of `AppDataFetcher`, if the `needsInitialFetch` prop is true.

Looking closer, to see when that might happen...`needsInitialFetch` is the only prop, and there's no state or context, and this is a PureComponent, so `componentDidUpdate` won't fire unless the value of `needsInitialFetch` changes from `false` to `true` or vice-versa. 

...Which means, the several cases in `sessionReducer` where we set `needsInitialFetch: true` will be ineffective at firing the initial fetch unless the previous value for `needsInitialFetch` was false. I'm...not yet sure what any active "gotcha" cases are. But we'll probably want to focus on making sure that it's not `true` when we mean it to be `false`.

In particular, I'm thinking of how to make this happen with the steps proposed at https://github.com/zulip/zulip-mobile/issues/4165#issue-640704691.

`LOGOUT` and `INITIAL_FETCH_COMPLETE` are the two actions that currently cause `needsInitialFetch` to be false. Would it be harmless to stick an `INITIAL_FETCH_COMPLETE` to abort on the timeout, along with the `dispatch(navigateToAccountPicker())` you've suggested, @gnprice? Or maybe there's another action we should invent, like `INITIAL_FETCH_FAILED`.

**Comment by gnprice** [comment] 2021-04-13 18:47
Closing because we don't have information to be able to debug the interaction with the server.

We have #4165 open for a change related to this that we realized we should make.

**Closed by gnprice** 2021-04-13 18:47 UTC
Labels: P1 high-priority, a-data-sync
