### ISSUE TITLE
Downloading attachment from the app requires logging in with the default browser

### ISSUE THREAD

**Issue by agrawal-d** [zulip/zulip-mobile#3805] opened 2020-01-15 05:38 UTC
**Steps to reproduce**
1. In you mobile device, If logged in to Zulip in the default browser, log out of it.
2. Download the attachment from [this narrow](https://chat.zulip.org/#narrow/stream/49-development-help/topic/Database.20schema) using the app.

**What Happens**
A browser window opens up to download the attachment.

**What is expected**
File should automatically download using the device's download manager.

Very similar to https://github.com/zulip/zulip-mobile/issues/2816

**Comment by agrawal-d** [comment] 2020-01-15 05:40
If this can be considered as a duplicate of https://github.com/zulip/zulip-mobile/issues/2816, please close this.

**Comment by ray-kraesig** [comment] 2020-01-16 01:28
This is related to the discussion in #2816, but it's distinct from what was asked for in that issue's opening post.

Closing as a duplicate of #3303 instead!

**Closed by ray-kraesig** 2020-01-16 01:28 UTC
