### ISSUE TITLE
Make the user log back in when the credentials aren't valid anymore

### ISSUE THREAD

**Issue by YagoGG** [zulip/zulip-mobile#2770] opened 2018-07-09 07:25 UTC
If a user regenerates their API token, the server will reply with an HTTP 401 error whenever the app asks for data. However, no feedback is provided to the user, which results confusing.

# Steps to reproduce

1. Log in as any user in the mobile app.
2. Go to the user settings in the web client, and generate a new API key (under *Your account*).
3. Try to interact with the mobile app by going to a stream or the home view. The app won't display any information, and will be stuck loading forever.

# Expected behavior

I would expect the app to kick the user out, and let them know about the situation: their credentials have changed, and therefore login back again is required.

From a longer term perspective, I wonder whether it may be worth having an endpoint in the REST API that works like the current `/fetch_api_key`, but only generates a per-application token (sort of how the OAuth flow works in some other platforms). This way, changes in the user's credentials or main API key wouldn't affect other services, unless the user revokes the authorization for that specific app.

---

@zulipbot label "bug"

**Comment by jainkuniya** [comment] 2018-07-09 08:37
Will be fixed by #2118.
Updating #2118. 👍 

@zulipbot claim

**Comment by borisyankov** [comment] 2018-07-09 08:54
I also expect this is the behavior if you change your password.

**Comment by YagoGG** [comment] 2018-07-09 08:59
I did a quick test in my dev env and apparently changing your password doesn't affect your API key, so it shouldn't be a problem if the user changes the password once they've already logged in.

**Comment by borisyankov** [comment] 2018-07-09 09:11
This is good for us since fewer cases currently break the app.
But I think we might consider this a bug and we **should** change the key on password change.
Do you want to check with the `zulip/zulip` guys about that?

**Comment by borisyankov** [comment] 2018-07-28 17:06
@synicalsyntax reported the same issue caused by different actions:
Changing user's email also causes the stored authentication information to be invalid resulting in failed login attempt.

**Comment by jainkuniya** [comment] 2018-07-30 05:18
Will rebase #2560, tonight 👍

**Comment by gnprice** [comment] 2019-12-06 00:55
This was fixed by #3254 . It looks like we'd forgotten about this thread; we duplicated the issue as #3253.

**Closed by gnprice** 2019-12-06 00:55 UTC
Labels: bug, zz-in progress
