### ISSUE TITLE
Tests currently not running on Mac

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#3179] opened 2018-11-30 17:33 UTC
Running `flow` gives an error:
```
src/boot/ReactotronConfig.js:5:23 Cannot resolve name __TEST__.
const inTest = typeof __TEST__ !== 'undefined' && __TEST__;
```

Running `test:lint` gives a different error:
```
$ files=( $(tools/files-changed | grep '^src/.*\.js$') ) || exit 0 && eslint --max-warnings=0 ${files[@]}
error: unknown option `long'
usage: git merge-base [-a | --all] <commit> <commit>...
   or: git merge-base [-a | --all] --octopus <commit>...
   or: git merge-base --independent <commit>...
   or: git merge-base --is-ancestor <commit> <commit>
   or: git merge-base --fork-point <ref> [<commit>]

    -a, --all             output all common ancestors
    --octopus             find ancestors for a single n-way merge
    --independent         list revs not reachable from others
    --is-ancestor         is the first one ancestor of the other?
    --fork-point          find where <commit> forked from reflog of <ref>

fatal: ambiguous argument '': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by gnprice** [comment] 2018-12-01 00:42
I don't reproduce the `flow` issue:
```
zulip-mac:mobile greg$ git log -n1 --oneline
8271d637 (HEAD, upstream/master, upstream/HEAD, master) caughtUp: Correctly handle the counterfactual that `!msg.flags`.

zulip-mac:mobile greg$ node_modules/.bin/flow
No errors!
```

(Just `yarn run flow` isn't working for me at all on this machine, apparently because of an old `yarn` version... working on updating that.)

Can you add more details? E.g. a terminal transcript, with the exact command you're running and the complete output.

The symptom looks like for some reason your Flow isn't seeing the file `flow-typed/globals.js`. I added that file in the same commit as the use of `__TEST__` itself.

**Comment by gnprice** [comment] 2018-12-01 00:47
Cool, `yarn` upgraded, and `yarn flow` itself works:
```
zulip-mac:mobile greg$ yarn flow
yarn run v1.12.3
$ /Users/greg/z/mobile/node_modules/.bin/flow
No errors!
✨  Done in 0.19s.
```

**Comment by gnprice** [comment] 2018-12-01 00:52
I reproduce the other issue. It's because macOS ships a `getopt` command that is literally from the '90s:
```
zulip-mac:mobile greg$ man getopt | tail -1
BSD                              April 3, 1999                             BSD
```
and was an exercise in nostalgia even then, harkening back to... the '80s at latest, maybe '70s?
```
zulip-mac:mobile greg$ man getopt | grep -B1 'Bell version'
     Written by Henry Spencer, working from a Bell Labs manual page.  Behavior
     believed identical to the Bell version.  Example changed in FreeBSD ver-
```
Kind of an obvious failure mode in retrospect, though; I should have tested.

I'll sort out a fix. Thanks for the report.

**Comment by gnprice** [comment] 2018-12-01 01:11
Pushed a fix for the `test:lint` / `getopt` issue -- thanks again!

Let's make the `flow` thing a separate issue, if you're still seeing it.

**Closed** 2018-12-01 01:11 UTC

**Comment by borisyankov** [comment] 2018-12-03 15:12
Killing and restarting the `Flow` process fixed this issue.
