### ISSUE TITLE
No compose box for private messages

### ISSUE THREAD

**Issue by Lyla-Fischer** [zulip/zulip-mobile#1453] opened 2017-11-23 19:32 UTC
There is no compose box for private messages, either replying to a PM or initiating a new PM.

**Comment by borisyankov** [comment] 2017-11-24 08:25
Thanks for reporting this issue.
This is the first time I hear about it and I can not reproduce it.
Can you tell me what platform is this? Are you running the app from the app stores or compiling from the repo?

**Comment by Lyla-Fischer** [comment] 2017-11-27 14:51
It's on android, and I'm getting it from the Play Store.

**Comment by Lyla-Fischer** [comment] 2017-11-27 14:57
Yep. It's the new one. And I'm on Android 7.0 Nougat

**Comment by Lyla-Fischer** [comment] 2017-12-10 16:30
I just discovered that you seem to be able to get to private messages in two different ways, and one of them has a compose box and the other one does not. If you go to the top messages mode, you don't get a compose box, and if you go to the bottom one, you do.
![tempfileforshare_20171210-112800](https://user-images.githubusercontent.com/549661/33806947-730a8bf6-dd9d-11e7-8c39-c1a945b2a32f.jpg)

**Comment by borisyankov** [comment] 2017-12-10 21:47
Great that you added a screenshot! I think I know what is happening now ;)

When you click the 'private' messages on top, you get a list of private messages.
When you click the 'conversation' button on the bottom, you get a list of conversations you've had (but not the messages). If you click on any of these, you will narrow to that conversation and there will be the compose box.

Does that make sense?

**Comment by borisyankov** [comment] 2018-01-06 17:28
Closing as resolved/not a bug.

**Closed by borisyankov** 2018-01-06 17:28 UTC
Labels: bug

**Comment by borisyankov** [comment] 2018-02-09 22:00
Implemented with #1898
