### ISSUE TITLE
Messages never load

### ISSUE THREAD

**Issue by EmilyRosina** [zulip/zulip-mobile#5662] opened 2023-02-15 09:46 UTC
Whatever I try, they never load.. on ANY stream/topic.

I tried:
- refreshing the app
- restarting my phone
- reinstalling the app

I'm on andriod (Samsung S9+).
App version `v27.200`.

![Screenshot_20230215-094004_Zulip](https://user-images.githubusercontent.com/21045073/218991662-5d0fc184-8c04-4ac4-9626-cda1f4a01199.png)

---

I also noticed that a bunch of other screens are empty too and never load...

![Screenshot_20230215-094758_Zulip](https://user-images.githubusercontent.com/21045073/218993630-864c78ed-9d6d-4666-aac4-af7ea4a4d436.png)

![Screenshot_20230215-094806_Zulip](https://user-images.githubusercontent.com/21045073/218993677-dbdc345b-af5c-49af-93a6-6f8b7c52968e.png)

**Comment by chrisbobbe** [comment] 2023-02-17 00:28
Hi @EmilyRosina, thanks for the report!

To help diagnose the issue, would you be interested in testing if the problem seems to be specific to that organization? I'm curious if you see the same symptom when connected to a different org, such as the [Zulip Development Community](https://zulip.com/development-community/).

**Comment by chrisbobbe** [comment] 2023-02-17 00:43
Also, I'm curious: after you uninstalled and reinstalled the app, do you remember if the app made you log in again? (If so, you would have entered your org URL, then entered a password or used a third-party auth provider, like "Sign in with Google".)

We're aware that (as odd as it sounds), uninstalling an app sometimes doesn't clear all its data: https://stackoverflow.com/questions/33169618/an-android-app-remembers-its-data-after-uninstall-and-reinstall

If you were already logged in after reinstalling the app, then some data wasn't cleared when you uninstalled it. I'd be interested to know if clearing the cache or the app data helps with this issue. You should find a "Clear data" button and a "Clear cache" button in Zulip's `App info` -> `Storage`. (I'd try "Clear cache" first, as I expect "Clear data" will log you out of your Zulip account in the app.)

Please let me know if I can make any of this clearer; I wrote this in a bit of a rush but definitely want to diagnose and fix the issue. 🙂

**Comment by EmilyRosina** [comment] 2023-02-17 01:17
Hi @chrisbobbe 

Also some additional info about my org, I can access it perfectly well via the Linux app and also in the web app via the browser. So it's just my phone app that's the issue.

I tried all of what you said:

1. `Clear cache` **still have the problem**
1. `Clear data` **still have the problem**
1. Join the [Zulip Development Community](https://zulip.com/development-community/) org, using my Github account and access via the browser for now **I am facing a never-ending loader there now** :weary:
  _So gonna guess that didn't work either :sweat:_
  _I have also tried refreshing the page, clearing LS/SS and closing opening my browser (Chrome) as well.. nada is helping.. so i'm a bit stuck on that point too now :sweat_smile:_


<details>
<summary>Errors i'm getting in the console for point 3.</summary>

![image](https://user-images.githubusercontent.com/21045073/219524318-e2ff20da-26da-4e81-a908-242cd1b4a71b.png)

```
Unknown user_id in get_by_user_id: 26065
(anonymous) @ blueslip.ts:34
```

```
jQuery.Deferred exception: Cannot read properties of undefined (reading 'date_joined') TypeError: Cannot read properties of undefined (reading 'date_joined')
    at Ae (https://chat.zulip.org/static/webpack-bundles/app.77c4554afb274c5ea0d8.js:2:82850)
    at https://chat.zulip.org/static/webpack-bundles/app.77c4554afb274c5ea0d8.js:2:105098
    at Module.I (https://chat.zulip.org/static/webpack-bundles/app.77c4554afb274c5ea0d8.js:2:53861)
    at HTMLDocument.<anonymous> (https://chat.zulip.org/static/webpack-bundles/app.77c4554afb274c5ea0d8.js:2:105055)
    at c (https://chat.zulip.org/static/webpack-bundles/251.f67b7a0206a58740f79e.js:2:142627)
    at l (https://chat.zulip.org/static/webpack-bundles/251.f67b7a0206a58740f79e.js:2:142929) undefined
```

```
Uncaught TypeError: Cannot read properties of undefined (reading 'date_joined')
    at Ae (ui_init.js:589:44)
    at ui_init.js:721:9
    at Module.I (blueslip.ts:239:17)
    at HTMLDocument.<anonymous> (ui_init.js:720:14)
    at c (jquery.js:3830:29)
    at l (jquery.js:3898:12)
```
</details>

**Comment by EmilyRosina** [comment] 2023-02-17 01:23
3. **Update** Ah - tried an incognito tab and it loaded :rocket: 

I am trying to login just via my google account directly, but still facing a similar neverending loader problem. I think I might chalk it upto Google being messed up a bit atm.. will try again tomorrow.

**Comment by chrisbobbe** [comment] 2023-02-18 02:25
Oh no! I'm sorry you've been so unlucky with these bugs.

We hope to have a fix for the chat.zulip.org bug out this evening. PR zulip/zulip#24415 was recently merged to mitigate a recent regression, and I expect it'll be deployed later this evening, after which you can try chat.zulip.org in the web app again.

**Comment by EmilyRosina** [comment] 2023-02-18 18:43
Hey @chrisbobbe I have a slightly irritating update :sweat_smile: 

My phone ran out of battery yesterday... and when I charged it and loaded it up... I could see the messages again. I have no rhyme nor reason that goes anyway to help explaining this :grimacing: But - good news is that I _can_ indeed see messages again.

I guess maybe my phone needed a full power off instead of a restart :woman_shrugging: no idea.. but that's my best guess.

**Comment by chrisbobbe** [comment] 2023-02-21 22:40
Ah! 😅 Thanks for the update, and I'm glad it's working again! I'll close this for now, but if you see the same symptom again, please let us know and we'll re-open.

**Closed by chrisbobbe** 2023-02-21 22:40 UTC
