### ISSUE TITLE
Make app layout compatible with split screen use.

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#1667] opened 2017-12-30 20:31 UTC
Current behaviour:
![screenshot_20171230-120713](https://user-images.githubusercontent.com/18511177/34457156-652afe76-edce-11e7-8bbd-665e9af7d937.png)

https://chat.zulip.org/#narrow/stream/mobile/subject/Crash.20when.20opening.20images/near/417963

**Comment by HarshulSharma000** [comment] 2018-03-18 12:43
How about we dynamically resize the components with parent view's dimensions?

**Comment by borisyankov** [comment] 2018-03-18 14:01
How do you mean to implement that?
These issues likely exist in many screens and can be fixed one-by-one sometimes in different ways.
Feel free to work on any of the screens that exhibit this behavior.

**Comment by HarshulSharma000** [comment] 2018-03-18 16:12
Actually my device does not have split screen functionality, So I can't reproduce this issue here. But Dimensions component of react native does provide listeners:-
https://facebook.github.io/react-native/docs/dimensions.html#addeventlistener
Also, we get the changed dimensions of our view:-
https://facebook.github.io/react-native/docs/view.html#onlayout
These could be used to get changes and then resize components accordingly. Or I suggest we should fire an action to change the value of currentScreenDimensions in Redux store that way change could be propagated to whole application.

**Comment by borisyankov** [comment] 2018-05-19 13:18
We have made improvements in this area.
Further work to make the UI more flexible is always welcome.
We no longer need to track that explicitly.

**Closed by borisyankov** 2018-05-19 13:18 UTC
