### ISSUE TITLE
Scrolling is often laggy

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#961] opened 2017-08-01 22:01 UTC
On iOS, when in the message view (narrowed to a stream), if I scroll around a bit, the app often doesn't respond to some of my swipes. That is: I touch and swipe to scroll, it starts moving normally; then I touch again and try to swipe either to scroll further or to stop scrolling; and nothing happens, just as if I hadn't touched the screen at all.

This behavior is very unusual in my experience as an iPhone user (might happen very occasionally, but basically no app I've used routinely suffers it), and it sticks out. I imagine what's happening is something like the relevant thread being busy and not responding to the scroll event, but I don't know enough about how the app actually works for that to be more than speculation.

**Comment by gnprice** [comment] 2017-08-01 22:02
(I'm on 1.0.15 (1), the build recently uploaded to TestFlight.)

**Comment by borisyankov** [comment] 2017-08-02 14:16
Your speculation is likely on point. Me and @Sam1301 will improve this further.
Message rendering is for sure part of the problem and possibly the only problem. We need to make sure we confirm where the CPU cycles go (just a note to Saumya, it is often the case we are over confident we know what the reason for some slow down is, and when we fix the cause, the problem does not go away, so we just need to make sure our hunch is right).

We might be able to fix something, but if not, our replacement of the MessageList with a FlatList or WebView will be the solution. 

The likely cause is: rendering of messages is a UI blocking operation, and we don't have much control over it.

**Comment by gnprice** [comment] 2017-08-03 00:41
Makes sense -- sounds like a good plan!

**Comment by borisyankov** [comment] 2017-09-23 01:47
@gnprice wanna try the latest version? Should be smoother now.

**Comment by gnprice** [comment] 2017-09-25 18:54
Indeed -- much smoother! I just installed 1.0.29 from TestFlight and played around with it some. Very nice.

There is still an occasional hiccup, which I imagine has a different cause so maybe this issue should be closed and a new one opened. Specifically, it looks like when the app gets a new batch of old history, the UI freezes briefly (like 400ms). One symptom is that any scrolling stops (and doesn't resume after, until I swipe again); another is that if I'm at the top of the existing history, the "Z" spinner at the top freezes for that period until the newly downloaded old messages appear in its place.

**Comment by borisyankov** [comment] 2017-10-20 12:04
I am closing this, as we made most (or all) of the perf optimizations related to scrolling.
We can open another issue if another optimization is needed.

**Closed by borisyankov** 2017-10-20 12:04 UTC
Labels: bug
