### ISSUE TITLE
Some emoji glyphs are missing for reactions on some phones

### ISSUE THREAD

**Issue by SunkyeongLee** [zulip/zulip-mobile#3181] opened 2018-11-30 21:18 UTC
When adding a reaction to any post, some emoji icons are not appearing properly.
Still the emoji doesn't appear correctly after being selected to add reaction.
In ios works good but it happens on android version.

![inkedscreenshot_2018-11-30-14-59-15_li](https://user-images.githubusercontent.com/25357982/49315374-1ac15000-f4b3-11e8-867b-f19660fcf482.jpg)
![inkedscreenshot_2018-11-30-15-00-07_li](https://user-images.githubusercontent.com/25357982/49315375-1ac15000-f4b3-11e8-80a5-6b9861f1cf4c.jpg)
 
https://youtu.be/heZ90JrH3GQ

**Comment by gnprice** [comment] 2018-12-01 04:30
Interesting -- thanks @SunkyeongLee for the report and those screenshots!

These work fine for me -- app version 20.0.103, on stock Android 9.0 (on a Pixel 2 XL). A few questions to help us diagnose:
* What Android version do you have, and what model of phone?
* If you try typing, say, `:ac` into the compose box, do these emoji show up correctly in the autocomplete? What if you send a message with these emoji in them -- do they look right?

One first thought I had is quick to be ruled out; some of the emoji that work fine in your screenshot, including `:action:` and `:agony:`, are outside the BMP (i.e. their codepoints are 5 hex digits long, like U+1F3AC `:action:`, rather than 4 or less.) So it's not a bug that's triggered by something trying to handle everything 16 bits at a time and getting those wrong.

**Comment by SunkyeongLee** [comment] 2018-12-02 17:31
My android version is 5.0.1 and the model is LG-F240S.
Hope it helps.

![screenshot_2018-12-02-11-24-46](https://user-images.githubusercontent.com/25357982/49342842-c12d6280-f625-11e8-9dc4-90a26d4538b3.png)
![screenshot_2018-12-02-11-27-15](https://user-images.githubusercontent.com/25357982/49342843-c4c0e980-f625-11e8-9536-83bbe90c7263.png)
![screenshot_2018-12-02-11-24-26](https://user-images.githubusercontent.com/25357982/49342844-c7234380-f625-11e8-874b-db792812bd56.png)

**Comment by chrisbobbe** [comment] 2020-02-07 22:49
Closing this to continue progress at https://github.com/zulip/zulip-mobile/issues/3885, which starts off with (hopefully!) some steps toward a working solution. Thanks for the report, @SunkyeongLee! 🙂

**Closed by chrisbobbe** 2020-02-07 22:49 UTC
Labels: a-Android, a-emoji
