### ISSUE TITLE
iOS: Push notifications sent for muted streams

### ISSUE THREAD

**Issue by tthoma24** [zulip/zulip-mobile#1314] opened 2017-10-16 19:40 UTC
The UI claims that push notifications will not be sent for muted streams unless you are mentioned, but that doesn't seem to be the case. I've been receiving notifications for a muted stream even when I am not mentioned.

**Comment by borisyankov** [comment] 2017-10-16 19:57
@kunall17 do you know anything about that?
Also, likely this needs to be handled on the backend, so pinging @timabbott and @showell

**Comment by timabbott** [comment] 2017-10-17 00:16
If this were an issue, it would be on the backend, not the mobile app.

**Comment by tthoma24** [comment] 2017-10-17 02:27
I’m not sure what you mean by if it’s an issue. It’s definitely an issue for me. Should I file a bug on the server repo? Provide more info? Something else?

**Comment by timabbott** [comment] 2017-10-17 04:46
@tthoma24 sorry I was in a hurry and attempting primarily to communicate with @borisyankov here.  What I mean is just that the server is where the logic is that decides whether a push notification is triggered or not, so whatever the issue is here is almost certainly in the server code.  We'll move the issue if needed once we know more exactly what it is.

@tthoma24 can you check your settings for the stream in question for whether you have the "send push notifications for messages sent to this stream" setting checked in addition to the stream being muted?  Also, can you confirm whether the stream is muted or just the topic in the stream is muted?  

If you can provide me with a specific stream name where you saw this happen, I can check these things directly, if that's easier for you.

**Comment by tthoma24** [comment] 2017-10-17 19:32
Yes, that setting is checked (but greyed out since the stream is muted)

**Comment by timabbott** [comment] 2017-10-18 05:43
This is actually a backend bug; I'll take care of it.

**Comment by timabbott** [comment] 2017-10-18 05:50
Fixed in master, thanks for the report @tthoma24!

**Closed by timabbott** 2017-10-18 05:50 UTC
Labels: bug, in progress
