### ISSUE TITLE
Rename "Conversations" to "Private messages" (tablet UI)

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#5448] opened 2022-07-22 19:10 UTC
The tablet mobile UI shows names of tabs in the bottom shortcut bar:

![179893547-04eaa273-9809-4da9-905f-ea03c8c040a7](https://user-images.githubusercontent.com/2090066/180507348-174eca08-fb7f-4370-a05b-8f36ca88701e.png)

As [discussed on CZO](https://chat.zulip.org/#narrow/stream/48-mobile/topic/.22conversations.22.20tab/near/1407736), we should rename "Conversations" to "Private messages" for clarity.

**Comment by Jcruz525** [comment] 2022-07-22 20:52
I would like to work on this issue!

**Comment by chrisbobbe** [comment] 2022-07-22 20:53
Thanks, @Jcruz525! I've just assigned it to you.

**Comment by Jcruz525** [comment] 2022-07-22 21:17
Hello, @chrisbobbe could you possibly help me navigate to where the file is located. I am relatively new to contributing and I am having trouble finding the file mentioned in the original comment.

**Comment by chrisbobbe** [comment] 2022-07-22 21:26
Sure! You should start with setting up a development environment using our [guide](https://github.com/zulip/zulip-mobile/blob/main/docs/developer-guide.md). Please let us know if you run into problems with that, in the #mobile stream in the [Zulip development community](https://zulip.com/development-community/). (That's a better place than GitHub for any complicated debugging discussions.)

The "Conversations" label is set in the file src/main/MainTabsScreen.js.

**Comment by Jcruz525** [comment] 2022-07-22 21:30
Thanks @chrisbobbe

**Comment by fjorn-x** [comment] 2022-07-23 05:24
Hello, I would like to work on this issue

**Comment by dootMaster** [comment] 2022-07-23 18:51
Hi all, I'd like to work on this if there's still space.

**Comment by rohinish404** [comment] 2022-07-25 13:12
i'd like to know if the issue is still there. I think i can work on this.

**Comment by pratyaksh1610** [comment] 2022-07-26 09:55
@chrisbobbe Actually I started working on this issue when it was mentioned right away, this is my first contributiom so I was not aware about getting assigned. 
I have raised a PR for the same.
.
.
Thankyou
Pratyaksh

**Comment by dootMaster** [comment] 2022-08-04 04:40
Hi @pratyaksh1610, I'm not part of Zulip dev but I've taken a look at your PR. I think your commit message could use some tidying up according to the guidelines established here in the [Commit Messages](https://zulip.readthedocs.io/en/latest/contributing/version-control.html#commit-messages) section of the Zulip docs. Let me know if you need any help, although the section provides some great examples.

**Comment by pratyaksh1610** [comment] 2022-08-04 05:47
Hi @dootMaster , thankyou for helping me out. I saw the project history and changed the commit message accordingly , stating the name of the issue and the change that I have made. Do let me know where I can improve.
Thanks.

**Comment by dootMaster** [comment] 2022-08-04 05:59
@pratyaksh1610 
No problem, here to help. It looks like you're missing the commit message body and the formatting could be improved. These things are further explained in the doc I linked above.

**Comment by pratyaksh1610** [comment] 2022-08-04 06:58
PTAL @dootMaster

**Comment by dootMaster** [comment] 2022-08-04 07:01
Nice work! @chrisbobbe

**Closed** 2022-08-04 18:37 UTC
Labels: help wanted, good first issue

**Comment by Jcruz525** [comment] 2022-10-11 08:51
I tried to make a pull request but it didn’t work … you can take it over if
they assign it to you!

**Comment by alya** [comment] 2022-10-11 22:27
@Jcruz525 , @siddoinghisjob , as you can see from the issue status, it has already been resolved.
