### ISSUE TITLE
Some emojis (digits and single letters) are displayed as text

### ISSUE THREAD

**Issue by ungps** [zulip/zulip-mobile#3395] opened 2019-03-12 20:12 UTC
Hello,

When composing a message, although `:0:` `:1:` `:2:`  ... `:10:` emojis are detected by the auto-completion system, they are displayed as plain text, not as emojis (:zero: :one: :two: ... :keycap_ten:). Also, they cannot be added as reactions. It seems that `:zero:` `:one:` `:two:` `:three:` ... `:ten:` work just fine in both cases. [Preview](https://gfycat.com/OilyIdioticAcornwoodpecker)

A similar problem is with `:a:` `:b:`, which are detected by the auto-completion system, but are not displayed at all (not even as `:a:` `:b:`). They can be added as reactions without any problem. [Preview](https://gfycat.com/ImpressiveSaltyGuineapig)

In the web application, `:0:` `:1:` `:2:` ... `:10:` are not in the list of emojis (but `:zero:` ... `:ten:` are) and are displayed as plain text. `:a:` and `:b:` are displayed correctly as :a: and :b: in messages. Neither `:digit:`, nor `:a:` `:b:` can be auto-completed.

I want to fix this, but I am not sure which would be the best solution. The easy solution would be to remove these emojis (`:digit:`) from emoji list (so the mobile app would be on par with web app). The other solution would be to add support for them.

P.S: Tested on Android 9.0, Zulip 23.3.112.

**Comment by timabbott** [comment] 2019-03-13 17:03
@HarshitOnGitHub may remember this issue on the webapp.

**Comment by HarshitOnGitHub** [comment] 2019-03-13 20:01
We need to update emoji code mapping from zulip master. Last update was based on the following commit https://github.com/zulip/zulip/commits/169de2f9cb9c4b0d30b943508d44453d3a4571f9 after which a change to remove number emojis was merged. https://github.com/zulip/zulip/commits/fc7e654d7b247eaf69afa513c62ae1922871f0eb
@jainkuniya FYI

**Comment by HarshitOnGitHub** [comment] 2019-03-13 20:04
Okay just checked #3100 seems a complete fix for these issues. :tada:

**Comment by gnprice** [comment] 2021-04-23 01:07
Thanks @ungps for this report!

The issue with `:1:` etc. and `:one:` etc. was fixed recently in #4551. (It would also be fixed by #2956, which is what #3100 was aimed at.)

The issue with `:a:` etc. turns out to be different -- it has the same cause as #3517. The issue is that the Zulip emoji database gives `:a:` a code of `1f170`, meaning that it should correspond to the Unicode codepoint U+1F170:
🅰 U+1F170 NEGATIVE SQUARED LATIN CAPITAL LETTER A

But with that codepoint on its own, the Unicode spec says it should be rendered as a text-style glyph, not an emoji-style glyph. That's what we do -- and then that text-style glyph runs into the same issue as `:check_mark:` used to (https://github.com/zulip/zulip-mobile/commit/718934acf47e78f2f9039485be38dbe86b531524) and doesn't show up properly in a light theme / light mode. In dark mode it *does* show up -- just with a less eye-catching glyph than it should. It's a lot like 🅰, rather than 🅰️. Previous chat discussion about text-style vs. emoji-style presentation (of different emoji): https://chat.zulip.org/#narrow/stream/3-backend/topic/unicode.20emojis/near/759360

I'll send a fix.

**Closed** 2021-04-23 01:59 UTC
Labels: a-emoji
