### ISSUE TITLE
Editing a message outside of the valid edit window should show a helpful message.

### ISSUE THREAD

**Issue by sstangl** [zulip/zulip-mobile#2902] opened 2018-08-18 17:49 UTC
Our organization is on zulipchat.com with a 10-minute edit window.

In the app, if a user attempts to edit a message that is outside of this window, a modal dialog pops up with just the text `API`. The user didn't know that they couldn't edit the message due to policy reasons -- they then thought that there was an error in the app or with the server.

Two options:
1. The "Edit" button should be grayed-out if the edit cannot be performed due to policy reasons, possibly with an explanation like "Edit (10 minutes only)", or something like that.
2. If the user manages to make an Edit request anyway, the returned message should explain something about the organization Edit policy.

**Comment by sstangl** [comment] 2018-08-18 17:54
Screenshot of what it looks like now: https://imgur.com/a/b6zNkhg

**Comment by jainkuniya** [comment] 2018-08-18 17:58
hi @sstangl Thanks for the feedback.
for
> The "Edit" button should be grayed-out if the edit cannot be performed due to policy reasons, possibly with an explanation like "Edit (10 minutes only)", or something like that.

We are tracking this under #2792

for
> If the user manages to make an Edit request anyway, the returned message should explain something about the organization Edit policy.

Will be fixed by #2871

**Comment by ray-kraesig** [comment] 2019-10-08 23:45
Closing as duplicate of #2780.

**Comment by ray-kraesig** [comment] 2019-10-09 01:13
Reopening and closing the other as duplicate instead: despite being later, this one has a clearer statement of the issue.

**Closed** 2019-10-10 20:23 UTC
