### ISSUE TITLE
Sharing through Zulip Android mobile App

### ISSUE THREAD

**Issue by marboxvel** [zulip/zulip-mobile#1102] opened 2017-08-28 21:05 UTC
Hi guys,

My team usually uses Zulip Android mobile app as a way to share their work or links. We all like the mobile app and like the good work you guys are putting into this project. We are wondering if we can have Zulip disappear after the share action completes. For example, if we are on a browser and want to share a website, we would get a list of apps to choose from. We would then select Zulip, choose the stream/topic, and hit send . Right now, after we hit send we don't get our browser back but we would be left inside Zulip.

Is it possible to change the way share works through Zulip Android app? We would all be so grateful to have this feature added to the Android mobile app. 

Thanks

**Comment by kunall17** [comment] 2017-08-29 03:24
@marboxvel Thanks for reporting this, You're talking about the other android app we have 
This one https://github.com/zulip/zulip-android | https://play.google.com/store/apps/details?id=com.zulip.android, right? 

And this feature is not available in this app.

> We would then select Zulip, choose the stream/topic, and hit send . Right now, after we hit send we don't get our browser back but we would be left inside Zulip.

Terminating the app on a message send would not be a good idea, maybe we could have a close button on the top or somewhere.
Anyways that project doesn't have any active development going on and we are focusing to improve this one! :)

**Comment by borisyankov** [comment] 2017-08-29 20:31
I am not sure what the zulip-android project had exactly... is it something like what @vishwesh3 had done (that I'll try to work with him to merge soon) https://github.com/zulip/zulip-mobile/pull/674

**Comment by marboxvel** [comment] 2017-08-29 23:25
@kunall17 Thanks for the quick reply. I'm talking about the one I got when I clicked the google store link you provided, the one that says "Native Android app for the Zulip open source group chat software". 
Of course I didn't mean that whenever you hit send the app should exit.  I'm talking about a scenario where you are on a different app, flipboard for example, and you want to share an article with the team. Wouldn't you prefer that after you finish sharing you get back to flipboard? why would you want to stay in Zulip and hit back or exit in order to get back to whatever the app you originally shared the article from?
Many apps have this functionality implemented, you may check Slack for example. 

@borisyankov Are you saying that the one @vishwesh3 is working on has this feature implemented? #674 

Thanks guys for the hard work.

**Comment by borisyankov** [comment] 2017-08-30 09:03
@marboxvel this is an improvement made in our new Android + iOS app (that will very soon replace the one you are using).

Actually, this might be a good time to ask you to have a look at the one that says 'Unreleased'. Any comments or issues you might have, we want to address them before the release.

**Comment by marboxvel** [comment] 2017-08-31 06:26
@borisyankov Sure. I would love to give you a hand. I already installed it. It looks more sleek than the official one, but it doesn't show up in the share list at all.

**Comment by borisyankov** [comment] 2017-08-31 09:10
Yeah, this PR is not yet merged. We would like to actually replace the current app with this one in the app store, so before we do that we need to make sure any feature that existed is at least as good or better than before. Any feedback in that regards of our current users is welcome 👍

**Comment by pulkonet** [comment] 2018-04-07 22:41
The app still doesn't show up in the share list, what could be the reason @borisyankov ? I would like to fix that.

**Comment by jainkuniya** [comment] 2018-04-08 17:56
@pulkonet soon it will be in master. #674

**Comment by gnprice** [comment] 2018-05-24 01:05
I believe this was a dupe of #117 (after sorting out the confusingness of our legacy app) -- closing in favor of that issue.

**Closed by gnprice** 2018-05-24 01:05 UTC
