### ISSUE TITLE
Message view often blanks after sending a message

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#1549] opened 2017-12-15 01:02 UTC
On 5.0.46 on iOS, when I send a message, often the message view goes blank. It looks like this:
![](https://chat.zulip.org/user_uploads/2/f3/Ush7KkGxR7ikhq-2jDKL-uZV/IMG_1663.PNG)
When I touch and scroll slightly, the messages reappear.

**Comment by borisyankov** [comment] 2017-12-15 22:22
@jainkuniya this might be related to the keyboard + scroll code you wrote. Could you have a look?

**Comment by jainkuniya** [comment] 2017-12-16 14:55
Main issue is, scrolling a list from JS. May be bug in react-native `scrollToEnd`/`scrollTo` methods (not completely sure, but yea) (or might be due to our custom scrollView native code is not updated). 

The issue is, scrollView is scrolled but its views are not updated. Resulted in white screen (no child views are displayed). Then when little scroll is performed, re-calcuation takes place and child views are updated.
Somewhat similar to https://github.com/facebook/react-native/issues/13202

> On 5.0.46 on iOS, when I send a message, often the message view goes blank.

Solution: remove scrolling related stuff (scroll to first unread message, scroll after sending message, and when keyboards pops) from JS part and implement them natively with proper checks. 
For Android issue of blank screen was fixed by https://github.com/zulip/zulip-mobile/commit/1e51768f7d96d9f4c6a05c2932db4bfd7f184242.

**Comment by jainkuniya** [comment] 2017-12-16 14:56
This will be automatically solved once we are done with `WebView`

**Comment by jainkuniya** [comment] 2017-12-16 14:56
@zulipbot claim

**Comment by jainkuniya** [comment] 2018-03-10 19:45
Now with the newer MessageList, it is no longer relevant, can be closed now.

**Closed** 2018-03-11 16:23 UTC
Labels: bug, in progress
