### ISSUE TITLE
Tapping + button removes text draft

### ISSUE THREAD

**Issue by namse** [zulip/zulip-mobile#5463] opened 2022-08-10 07:59 UTC
When I put some text, then if I press + button, it removes text what I typed. 

![image](https://user-images.githubusercontent.com/3580430/183847391-4ff542bb-8062-495b-ac29-d2209dec908f.jpeg)
I typed, then tap the + button,

![image](https://user-images.githubusercontent.com/3580430/183847456-a4d7ef50-fcc1-4e55-849e-10a666c73ec1.jpeg)

It's gone. 

I hope keeping text draft even when I press + button to put image before sending text.

**Comment by chrisbobbe** [comment] 2022-08-25 18:53
Thanks for the report! I believe this is caused by the same bug as #5291:

> the `RCTSinglelineTextInputView` is swapped out for a `RCTMultilineTextInputView`, which didn't get its native props updated.

and the planned fix for that bug (making the input permanently `multiline`, after #5141) will also fix this bug. Marking as high priority because this is such a frustrating bug for people who encounter it.

**Comment by chrisbobbe** [comment] 2022-10-20 03:31
We got another report of this: https://chat.zulip.org/#narrow/stream/48-mobile/topic/appfollow/near/1452309

**Closed** 2023-01-11 18:57 UTC
Labels: a-iOS, P1 high-priority
