### ISSUE TITLE
App crashes immediately upon opening

### ISSUE THREAD

**Issue by jhurwitz** [zulip/zulip-mobile#837] opened 2017-07-08 16:17 UTC
See https://chat.zulip.org/#narrow/stream/mobile/subject/crashes/near/246097

I (and at least one other person) can't use the iOS testflight app because it crashes immediately upon opening. Clearing app storage hasn't helped, and uninstalling/reinstalling also hasn't.

Additionally, there are no errors in Crashlytics, and no crashes in device logs when I connect my phone to Xcode.

**Comment by jhurwitz** [comment] 2017-07-11 04:22
Today's TestFlight update did not resolve the issue

cc @timabbott

**Comment by borisyankov** [comment] 2017-08-01 13:37
@jhurwitz have you tested the latest TestFlight? 
We have made lots of fixes, but even more importantly we now have a really good Sentry bug reporting, even if it still crashes for you, we'll catch it and rush a fix.

**Comment by jhurwitz** [comment] 2017-08-01 17:10
I stopped being able to repro the crash on July 14; you should ask someone who (as of recently) still could.

> mobile > crashes Jul 14
>
> Jacob Hurwitz: Mysteriously... I just opened the mobile app, and it didn't crash! This is the same version (1.0.4) that was crashing previously -- so maybe a server-side change fixed it?
>
> Jacob Hurwitz: (which would make sense, since I think a server-side change rather than a client update is what first broke my mobile app)
>
> Tim Abbott: Weird; we haven't made relevant changes to the servers.
>
> Tim Abbott: I guess it could be a data problem: some message was causing problems.
>
> Jacob Hurwitz: When the app did finally open I was logged into zero servers, so probably not a message causing issues
>
> Jacob Hurwitz: (remember, I'd deleted all app data several times, which includes auth info)
>
> Tim Abbott: Weird.
>
> Greg Price: Interesting!
>
> Greg Price: Still crashes for me, though -- tried it just now.

cc @gnprice

**Comment by gnprice** [comment] 2017-08-01 21:55
The 1.0.4 (1) on my phone still crashes on startup. Updating now to 1.0.15 (1)...

... and it seems to work! Cool.

Took about 6s on first startup before it showed any messages, sitting at the screen with a bunch of grayed-out-message-like placeholders.

On second startup, more like 3-4s and it shows a Zulip-green spinner instead of the placeholders.

Kind of laggy -- often goes unresponsive for a bit -- but I'll go find or file an issue that's about that. Glad to have it running!

What other users did we know were seeing the crash on startup? If we can't find anyone who can still reproduce it, it'd be reasonable to close this issue; we can always open a new one if a similar crash turns up later.

**Comment by timabbott** [comment] 2017-08-01 23:15
I was able to get a crash on login by typing the wrong thing, but nothing on startup.  So we probably accidentally fixed the startup issue.  See https://chat.zulip.org/#narrow/stream/mobile/subject/crash.20on.20login/near/260922 for the login issue.

**Comment by borisyankov** [comment] 2017-08-02 02:21
I was also crashing on my device. It wasn't with me to test, but getting home in few hours and will test. If it works for me too, then it really is fixed.

@gnprice there are things we can do to optimize the startup a bit still, so we will be working on this too (pinging @Sam1301 )

**Comment by borisyankov** [comment] 2017-08-21 09:54
This particular bug seems to be resolved.

**Closed by borisyankov** 2017-08-21 09:54 UTC
Labels: bug
