### ISSUE TITLE
Check mobile compatibility for limited guests

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#5787] opened 2023-11-08 20:58 UTC
We should make sure the mobile app is compatible with the changes being made in zulip/zulip#10970.

**Comment by gnprice** [comment] 2023-11-10 01:49
I've just taken a look at this, and I've sent #5790 to fix the two issues I found.

I think neither of those is a showstopper. So we should get those fixes out promptly, but not worry about some users still having old clients while encountering the new feature.

I was testing on an approximation of the real feature, though: I tried running https://github.com/zulip/zulip/pull/27544 in my dev server, but AFAICT that PR doesn't yet actually make it possible to enable the feature — it only lays the groundwork. So it'd be good to re-check compatibility when there's something more like a working version of the server feature which can be tried out.

---

#### Details on the severity of the two issues
* They're crashes, which is bad.
* But they happen only on relatively uncommon actions (tapping a message sender's name or avatar to go to their profile, or selecting "See who reacted" on a message), and only if the user involved is one you're not able to see, even though they sent or reacted to a message you're looking at.
* And I believe even getting into the latter situation is a fairly uncommon edge case: IIUC you can see any user you're in a stream with, and any user you have DM history with, so it'd have to be something like that the user has since left the stream.

#### Details on how I approximated the "limited guests" feature

I applied the following ad-hoc diff:
```diff
--- a/src/users/usersReducer.js
+++ b/src/users/usersReducer.js
@@ -14,2 +14,4 @@ const initialState: UsersState = NULL_ARRAY;
 
+const allowedUsers = new Set(["Cordelia, Lear's daughter", 'Polonius']);
+
 export default (
@@ -23,3 +25,3 @@ export default (
     case REGISTER_COMPLETE:
-      return action.data.realm_users;
+      return action.data.realm_users.filter(u => allowedUsers.has(u.full_name));
 
```
This causes the app, when it's first loading server data, to drop on the floor any users other than the two named. (And other than deactivated users and system bots, which this diff doesn't affect.) Then I logged into my dev server as Polonius, a guest user.

#### Details on what I tested

I explored various parts of the UI in the presence of unknown users, trying to think of all the various places we show information on a user:

* The inbox screen, and the DM-conversations screen. These behaved fine — any conversations involving unknown users were just omitted.

  IIUC any users we have DM history with should not be unknown, so this shouldn't even come up.

* The message list. This was fine — the name and avatar of a message sender shows up even if the user is unknown, because we get it from the message object anyway.

* Lists of all users: specifically the "New DM" screen and the "Add subscribers" (to a stream) screen. (There are a couple of other places these lists can appear, but they use the same code so I stopped after those two.) These worked fine — any unknown users just don't show up.

* Autocomplete for @-mentions. This worked fine — any unknown users just don't show up.

* The profile screen, and the "See who reacted" screen. These crashed as described above.

I also looked through the code:
* We have a `getUserForId` function which looks up a user by their user ID and throws if not found. (After all, until this feature, in the bulk of the app that could only be a sign of a bug.) This was the source of both of the crashes above. I looked at all call sites; the remaining two are harmless.
* I looked around the code for places where rather than showing UI, we're handling an event from the server, and where we might look up data on a user. All the ones I found are already using `tryGetUserForId` (the non-throwing version of `getUserForId`, and are doing something reasonable if they don't find the user.
* I also looked at where we handle opening a notification (and trying to navigate to the conversation). There too, if we don't find the user then we just fail gracefully rather than crash.

**Comment by alya** [comment] 2023-11-14 07:05
Awesome, thank you for the investigation and the detailed notes!

@sahil839 FYI

**Comment by chrisbobbe** [comment] 2023-12-19 23:53
I tested and confirmed that the avatar issue (zulip/zulip#28071) has been fixed. So from Greg's message above, I think the following is the only remaining item, and fixing it would close this issue?

> - Lists of users (the "user list" component found in several places including "New DM", and the autocomplete for @-mentions) include the unknown users and shouldn't. We can fix that once a planned server feature is added.

**Comment by sahil839** [comment] 2023-12-20 09:18
[965869d3f8e](https://github.com/zulip/zulip/commit/965869d3f8e855b80793fd64080ea19256d1955c) added client capability to not receive data for unknown users.

**Comment by gnprice** [comment] 2023-12-22 01:23
Thanks @chrisbobbe and @sahil839 for those updates! I've filed #5808 for the followup based on those. The compatibility is now thoroughly checked, so closing this issue.

**Closed by gnprice** 2023-12-22 01:23 UTC
Labels: P1 high-priority, webapp parity, server release goal
