### ISSUE TITLE
Draft saving does not always work

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#2921] opened 2018-08-27 15:32 UTC
The way we save the drafts does not guarantee their storage. This is apparent from looking at the code and was reported as a bug. (though it seems to not be too likely, it can definitely happen)

**Comment by chrisbobbe** [comment] 2020-02-13 08:29
Hmm, have we ever supported drafts in the mobile app? See also https://github.com/zulip/zulip-mobile/issues/3500.

**Comment by gnprice** [comment] 2020-02-29 00:46
We do indeed! You can demonstrate this like so:
* Go to some conversation, type something into the compose box, but don't send.
* Navigate back, then navigate again into the same conversation.
* The (draft) message you typed should be there in the compose box.

Or further:
* Now force-quit the app, relaunch it, and navigate again to the same conversation.
* The same draft message should again be there.

---

Unfortunately the original report here doesn't give any details of what was wrong; so it's hard to say if the problem Boris had in mind in 2018 is still there or has since been fixed. It'd be useful for someone to take a look, though, and see if they can either (a) find a change in the history that might have fixed a bug like this, (b) locate a bug like this by reading the code, or (c) reproduce a bug like this today.

**Comment by gnprice** [comment] 2021-04-10 01:07
Closing this, because without details of what was thought to be wrong it doesn't carry much useful information after so long and so many changes to the app.

If anyone spots a bug like this one, whether by reading code or otherwise, please do file a new issue.

**Closed by gnprice** 2021-04-10 01:07 UTC
Labels: a-compose/send, bug
