### ISSUE TITLE
Math rendering mangled on Android

### ISSUE THREAD

**Issue by jedbrown** [zulip/zulip-mobile#2929] opened 2018-08-29 04:06 UTC
Math displays fine in the browser, but renders poorly in the Android app. This with version 16.2.96 on Android 9:

![Example](https://user-images.githubusercontent.com/3303/44764756-8e4b6e00-ab0e-11e8-9cd7-85bf5b038e7c.png)

**Comment by borisyankov** [comment] 2018-08-30 00:12
Thanks for reporting this issue.
It will be resolved when we merge this PR #2690

**Comment by gnprice** [comment] 2018-09-24 23:13
Thanks for the report!

I believe this is a duplicate of #2660; closing in favor of discussion continuing there.

**Closed by gnprice** 2018-09-24 23:13 UTC
