### ISSUE TITLE
Recipient icons overflow in the navbar for group PMs with large no. of recipients

### ISSUE THREAD

**Issue by agrawal-d** [zulip/zulip-mobile#3940] opened 2020-02-29 10:55 UTC
Group PM screen:
![image](https://user-images.githubusercontent.com/7714968/75606159-ffa71b00-5b0f-11ea-9668-80f0675d0865.png)

**Comment by agrawal-d** [comment] 2020-02-29 11:00
Here's the webapp equivalent:
![image](https://user-images.githubusercontent.com/7714968/75606236-b1464c00-5b10-11ea-8884-b11e19e500ed.png)

They don't show profie pictures like we do.

**Comment by gnprice** [comment] 2020-03-02 19:45
Thanks for the report!

We should cut the list off, ideally with an ellipsis or something, when it overflows the space actually available to it.

There's no need for it to scroll or anything; the "info" icon at top right leads to a full list. And the case where you have more than like 6 other people in a group-PM thread is pretty pathological anyway, so that extra step is fine :slightly_smiling_face:

**Comment by chrisbobbe** [comment] 2020-03-05 02:57
This looks like a duplicate of https://github.com/zulip/zulip-mobile/issues/3700, which is in progress at https://github.com/zulip/zulip-mobile/pull/3786. It looks like that PR is cutting the list off, as you've said, but I'll mention the ellipsis over there. 🙂

**Closed by chrisbobbe** 2020-03-05 02:57 UTC
Labels: a-layout
