### ISSUE TITLE
Some mobile clients repeatedly registering for push notifications in same second

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#2128] opened 2018-03-24 21:03 UTC
I saw some server-side exceptions because we had 2 requests for a single push ID to register for push notification in the same second (this resulted in an exception because the timestamp was the same, and so our `token.save(update_fields=['last_updated'])` was failing).  Checking server logs more generally shows a pretty consistent pattern of clients trying to register for push notifications many times in the same second; and I see a similar pattern grepping our logs for the appropriate APNS endpoint.

(The below batch is all from a single IP address/username pair):

```
2018-03-23 23:58:49.189 INFO  POST    200  10ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-23 23:58:49.241 INFO  POST    200  17ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-23 23:58:49.280 INFO  POST    200  48ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-23 23:59:19.619 INFO  DELETE  200   7ms (db: 0ms/2q) /api/v1/users/me/android_gcm_reg_id
2018-03-23 23:59:22.328 INFO  POST    200  10ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-23 23:59:22.336 INFO  POST    200  16ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-23 23:59:22.352 INFO  POST    200  24ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-23 23:59:22.391 INFO  POST    200  47ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-23 23:59:22.447 INFO  POST    200   9ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-23 23:59:22.609 INFO  POST    200  23ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-23 23:59:22.650 INFO  POST    200  49ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-23 23:59:22.719 INFO  POST    200   9ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-23 23:59:22.876 INFO  POST    200   9ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-23 23:59:22.922 INFO  POST    200   9ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-23 23:59:22.994 INFO  POST    200   9ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-23 23:59:23.101 INFO  POST    200   9ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-23 23:59:23.111 INFO  POST    200   9ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-23 23:59:23.124 INFO  POST    200   9ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-23 23:59:23.149 INFO  POST    200  10ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-23 23:59:23.196 INFO  POST    200   9ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-23 23:59:23.269 INFO  POST    200   9ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-24 00:37:56.667 INFO  DELETE  200   8ms (db: 2ms/2q) /api/v1/users/me/android_gcm_reg_id
2018-03-24 00:37:59.562 INFO  POST    200  12ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-24 00:37:59.571 INFO  POST    200  11ms (db: 3ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-24 01:11:18.644 INFO  DELETE  200   7ms (db: 2ms/2q) /api/v1/users/me/android_gcm_reg_id
2018-03-24 01:11:20.933 INFO  POST    200   9ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-24 01:11:20.942 INFO  POST    200  10ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-24 01:11:21.738 INFO  POST    200   9ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-24 01:11:21.749 INFO  POST    200  10ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-24 01:11:44.862 INFO  DELETE  200   7ms (db: 0ms/2q) /api/v1/users/me/android_gcm_reg_id
2018-03-24 01:11:47.281 INFO  POST    200   9ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-24 01:11:47.288 INFO  POST    200  11ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-24 01:11:47.306 INFO  POST    200  29ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-24 01:11:48.076 INFO  POST    200   9ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
2018-03-24 01:11:48.113 INFO  POST    200   8ms (db: 2ms/3q) /api/v1/users/me/android_gcm_reg_id
```

This seems pretty clearly to be a bug in our mobile app code.

**Comment by borisyankov** [comment] 2018-03-24 23:29
Do you have any idea if this is something new or we just have not noticed until now?

**Comment by timabbott** [comment] 2018-03-24 23:55
The exception in question was first seen March 9 but has only happened like 5 times.  The blocks of repeated requests goes back at least to March 5 (probably even further).

**Comment by timabbott** [comment] 2018-04-26 16:49
This is fixed now, right?

**Comment by borisyankov** [comment] 2018-04-26 19:48
Yes! Closing.

**Comment by gnprice** [comment] 2019-01-30 23:23
I don't know why this was once believed to have been fixed (it's hard to tell because no commit or PR is mentioned), but it's still quite live. Here's some logs from just now:
```
2019-01-30 23:07:57.216 INFO pid:16311 [zr] 38.30.8.235     POST    200 376ms /api/v1/users/me/apns_device_token (greg@zulipchat.com via ZulipMobile)
2019-01-30 23:07:57.236 INFO pid:16298 [zr] 38.30.8.235     POST    200 396ms /api/v1/users/me/apns_device_token (greg@zulipchat.com via ZulipMobile)
2019-01-30 23:07:57.237 INFO pid:16309 [zr] 38.30.8.235     POST    200 394ms /api/v1/users/me/apns_device_token (greg@zulipchat.com via ZulipMobile)
2019-01-30 23:07:57.252 INFO pid:16313 [zr] 38.30.8.235     POST    200 408ms /api/v1/users/me/apns_device_token (greg@zulipchat.com via ZulipMobile)
```

The repro is simply to switch back and forth several times between two (or more) different accounts.

The cause is this logic:
```
const getTokenIOS = (auth: Auth, dispatch: Dispatch) => {
  NotificationsIOS.addEventListener('remoteNotificationsRegistered', async deviceToken => {
    dispatch(gotPushToken(deviceToken));
    await dispatch(sendPushToken(auth, deviceToken));
  });
  // ...
  NotificationsIOS.requestPermissions();
};
```
which runs as part of initial fetch, at startup or after logging into or switching to an account. Note it *adds a listener*; these accumulate, with the consequence that after switching accounts several times, there are several listeners, each prepared to tell a particular server about our APNs device token. The last line kicks off a sequence of consequences that ends up firing the event all those listeners are listening for.

On the Android side it's a bit trickier to reproduce, because since the recent c45fe7f5c (in 22.0.107) we only trigger the event if on the account we're switching *to*, the server hasn't already acknowledged hearing our token. But if you switch back and forth a few times, then log into a new account, or switch to an account you haven't used since upgrading to 22.0.107, the exact same behavior happens.

I'll fix this shortly as part of the ongoing overhaul of our notifications code. Reopening to clarify the background for the commit that will fix it.

**Closed** 2019-01-31 00:38 UTC
Labels: area: multi-org, area: notifications, bug
