### ISSUE TITLE
Image after upload is not being shown as image preview in chat

### ISSUE THREAD

**Issue by HarshulSharma000** [zulip/zulip-mobile#2126] opened 2018-03-24 16:45 UTC
**Description**-
Uploading an image into the chat either via clicking an image from in app camera or uploading an image from gallery. Results in the image being uploaded and sent but is not viewable within the chat. The image is viewable on full screen mode.
**Platform**: Android 6
**Steps to Reproduce**:-

- Go to any chat upload any image or click one within zulip.
- Image preview is not viewable.

**Comment by HarshulSharma000** [comment] 2018-03-24 16:45
@borisyankov  @jainkuniya  I would like to work on this. I guess we might be having a problem with image styling or rendering.

**Comment by pulkonet** [comment] 2018-03-24 16:48
I am not sure what you are talking about. I tried to upload an image and it got rendered in a second or so. Can you please elaborate the steps of reproduction?

**Comment by HarshulSharma000** [comment] 2018-03-24 17:02
![screenshot_20180324-222826](https://user-images.githubusercontent.com/25546227/37866616-21441b30-2fb3-11e8-8117-53a1300816d7.jpg)
@pulkonet After uploading getting this.

**Comment by pulkonet** [comment] 2018-03-24 17:04
I am not getting this, maybe this is because of your network speed.
My image is uploading properly.

Please check with others also.

**Comment by HarshulSharma000** [comment] 2018-03-24 17:10
Tried uploading three images images are viewable if you click over them. Basically on fully screen image mode they act normally. As for the internet speed tried wifi and mobile data. Both result in same.

**Comment by yorickvP** [comment] 2018-03-25 12:18
Also happens for me. It works when you click it but doesn't show in the short preview, even after an app restart.

**Comment by yorickvP** [comment] 2018-03-25 17:03
Some more debugging results in:
```
https://zulip.serokell.review/user_uploads/2/fb/qHoi7_Inm6TecnIpR6nr4xSv/Screenshot_20180325-141157.png Failed to load resource: the server responded with a status of 401 (Unauthorized)
```

Seems like the webview doesn't have the authorization to fetch these things.

**Comment by yorickvP** [comment] 2018-03-25 17:56
It seems to be pretty hard to get these authorization headers into that webview (in MessageListWeb.js), react doesn't support it on Android.

**Comment by HarshulSharma000** [comment] 2018-04-04 19:42
@zulipbot  claim

**Comment by borisyankov** [comment] 2018-05-18 23:14
Closing as fixed.

**Comment by elgandoz** [comment] 2021-09-10 14:46
@borisyankov @pulkonet this bug still happens on the latest version of Zulip (27.170) for both Android and iOS, for every single user of our self hosted server.

On the web app works fine.

I also tried on a test organisation in zulip.org and I get the same behaviour.

Not a network issue, since I'm fibre wifi, just streamed 4k video with no buffer.

Android app.
![Screenshot_20210911-000538_Zulip.jpg](https://user-images.githubusercontent.com/5859926/132871497-328e1d11-ffb4-42a8-8859-7840ac0e5b37.jpg)

Please reopen the issue.

**Comment by elgandoz** [comment] 2021-09-10 15:10
One thing I could notice is that in the chat, in the markdown code the link are relative, while in the lightbox (where it works) links are absolute.

Is there anything on the server side we can change?

**Comment by chrisbobbe** [comment] 2021-09-10 20:10
Thanks for the report, @elgandoz! I've opened a debugging thread on CZO, [here](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Image.20previews.20broken.20.28self-hosted.29/near/1254380). I agree that it doesn't seem to be a network issue.

**Comment by elgandoz** [comment] 2021-09-11 23:47
Hi all, as mentioned in the chat, this issues was caused by the old URL format for thumbnail, in an old version of the server (4.0-dev). I'm sorry having re-opened the issue, after trying with the latest stable the problem does not appear, we can close this one for good.

**Comment by chrisbobbe** [comment] 2021-09-13 18:02
> I'm sorry having re-opened the issue

No worries! 🙂 Glad to have learned what was going on, for any future similar bug reports. Please let us know if you run into other issues on the new version.

**Closed by chrisbobbe** 2021-09-13 18:02 UTC
