### ISSUE TITLE
Unable to remove emoji reaction when just added

### ISSUE THREAD

**Issue by agzuniverse** [zulip/zulip-mobile#2784] opened 2018-07-10 07:03 UTC
(edited by @gnprice after discussion below)

Tapping an emoji reaction you've made should remove it. But:

* It doesn't work if I just added the reaction here (the most common case in practice, I'm pretty sure).
* Also doesn't work if I just added it through the webapp.
* It *does* work if I previously added it, and only then went and loaded these messages.

---
(original report:)

Tapping on a reaction to a message by you does not remove it if it is the only reaction of that particular type on a message.

**Comment by borisyankov** [comment] 2018-07-10 07:21
Hmm, I cannot reproduce. For me, it worked.
What I encountered though is that if you create a reaction on the web and you are looking at the message on your phone, the reaction it does not appear.
This might be related and is worth investigating.

**Comment by jainkuniya** [comment] 2018-09-21 04:42
Got the reproduction, submitting PR soon 👍 

Thanks @agzuniverse  for the report.

@zulipbot claim

**Comment by gnprice** [comment] 2018-11-09 23:37
OK, having now read the code in #2983: that fix matches the pattern I just described.

More detail in #2806 (which I just closed as a dupe of this), including screenshots from Chrome devtools of our malformed requests and the server's responses.

**Comment by gnprice** [comment] 2018-11-09 23:44
I've updated the description at the top.

Another symptom -- I deduced this from the proposed fix in #2983, and just went and quickly reproduced:
* If someone else just reacted to a message while you were looking at it (i.e. while the app already knew about the message, I think), then tapping on the reaction doesn't do anything. It should upvote it.

**Comment by gnprice** [comment] 2018-11-12 20:35
Just added label `upstream: other`, because it turns out (as we learned [just now on the PR](https://github.com/zulip/zulip-mobile/pull/2983#issuecomment-438019051)) that the type error at the root of this issue is one that Flow completely fails to catch. :-/  The Flow issue is facebook/flow#6871 .

**Closed** 2018-11-12 20:39 UTC
Labels: P1 high-priority, bug, upstream: other
