### ISSUE TITLE
Self-PM appears in other PM conversations

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#3324] opened 2019-02-04 18:39 UTC
Steps to reproduce.
* Open any PM narrow other than self, so that `newer` `caughtup` for that narrow become true.
* Now open self narrow and send new message.
* Now again  narrow back to same narrow which you picked in step 1.

**Observation**
The message which we posted in step two (to self) is also visible in other narrow (which we picked in step 1,3)

Restart the app, all works fine.

Issue is why message got added to list of other narrow?

Because there is an issue in our `matchRecipients` of `isMessageInNarrow` in `narrow.js`.

As for all PM narrow, `normalizedRecipients === ownEmail` is true for self message.
Because in this condition we are not taking care of `narrow`, it just compare recipient in message and `ownEmail`.

@zulipbot claim

Will send a PR soon for this.

**Comment by borisyankov** [comment] 2019-02-04 19:18
Is that a bug though? This is how that works in the web app.

**Comment by jainkuniya** [comment] 2019-02-04 19:21
@borisyankov By "all private narrow" , I doesn't mean "All private message".
I mean all other private narrows.

(editing title to ` all other private narrows` )

**Comment by gnprice** [comment] 2019-02-25 22:43
Thanks @jainkuniya !

Following up on my comments on #3328, here's what I think would make a good fix for this bug:
* Add some unit tests that clearly demonstrate the bug. They should fail if run on master.
* I think the root cause of the bug is that `matchRecipients` is too complicated. So let's fix that.
* I think one of the reasons it became too complicated is that it's handling both 1:1 PMs and group PMs. Let's write each case separately.
* The group case can be a lot simpler than that `matchRecipients` function. Try writing it very simply.
* The 1:1 case can also be simpler. Try writing it out more explicitly. I think a conditional like `email === ownEmail ? ...` may help.

**Comment by gnprice** [comment] 2020-10-29 23:52
FTR, although #3328 refers to a "regression in `matchRecipients`", this bug is much older, and older than that function. It dates back to 2017-01 with commit d8faae9d7; it's present at that commit, and absent at its parent.

Before that point, the code had the opposite bug on self-1:1 messages: they didn't appear even in their own conversation narrow. That commit aimed to fix that, and introduced the puzzling `normalizedRecipients === ownEmail` condition mentioned above, and with it introduced this bug.

**Closed** 2020-11-03 00:42 UTC
