### ISSUE TITLE
Issues with sharing contents on the android Zulip app

### ISSUE THREAD

**Issue by marboxvel** [zulip/zulip-mobile#3726] opened 2019-12-15 18:05 UTC
I used to share contents through the android Zulip app, but suddenly about 2 months ago that feture is not working anymore. 

I started receiving the message "Error sending message" every time I try to share something through the app.

The app is the old Android app and is no longer in the play store

The new app has no sharing option. It doesn't show up in the share list when I try to share any content. It would be great to have the new app be able to share contents from other apps.

**Comment by ray-kraesig** [comment] 2019-12-17 19:53
> The app is the old Android app and is no longer in the play store

The old Android app is no longer supported. It'd be interesting to know why it suddenly stopped working, but I suspect that would have been a server-side change.

> The new app has no sharing option. It doesn't show up in the share list when I try to share any content. It would be great to have the new app be able to share contents from other apps.

This is another matter, though. It's covered by #117, and ordinarily I'd promptly close-as-duplicate – but since this is a frequently-requested feature, I'll leave this issue open for now, to help keep it on our radar through the holidays.

**Comment by marboxvel** [comment] 2019-12-19 19:19
Thanks @ray-kraesig for shedding some light on the new app issue #117, but it was created 3 years ago and hasn't yet resolved. When do you think we will be able to share through the new app? My group and I use that feature a lot and we are now not able to share anything through Zulip. It is critical to our work. We would appreciate it so much if work on that ticket gets moving because I don't see much activity there.

Thanks a lot for the wonderful work.

**Comment by ray-kraesig** [comment] 2019-12-24 00:11
I'll take a closer look at it if I have some time before New Year's, but I'm sorry to say I'd be surprised to see it before February: we're a little undermanned through the holiday season, and a quick search for existing React Native sharing solutions brings up what looks like a bunch of sharp edges that will have to be taped over (metaphorically speaking).

**Comment by maltokyo** [comment] 2020-03-07 22:55
Hello. Any testing help or anything needed. Keen for this!

**Comment by gnprice** [comment] 2021-10-18 22:55
Closing this as a duplicate of #117, which happily has in the meantime been resolved.

Thanks @marboxvel for the report!

**Closed by gnprice** 2021-10-18 22:55 UTC
Labels: duplicate
