### ISSUE TITLE
Messages not loading until force-quit; new messages not appearing

### ISSUE THREAD

**Issue by jphilipsen05** [zulip/zulip-mobile#3657] opened 2019-10-21 17:25 UTC
When opening messages on iPad OS the messages do not open. I can force quite the app, to get the messages to load after quitting a few times, but it does not load right away until I quit. 

The first time I click into any app I get a loading page. Then when I force quit the app it brings the messages back up. When the messages are displayed I can not get new messages until I quit the app again. The sometimes I get the loading screen and have to quit again in order to get the message stream to load. 

I am getting this error on the current version in the app store and in the test flight versions since I knew iPad OS was new and wasn't sure if that was causing the issues. 

Let me know if you have any questions or need anything else. 

![6679](https://user-images.githubusercontent.com/10887427/67227900-0947a600-f3ed-11e9-824e-9646c9007caf.jpg)

**Comment by gnprice** [comment] 2019-10-21 18:13
Hmm! Thanks @jphilipsen05 for the report. That is a pretty bad set of symptoms.

> The first time I click into any app I get a loading page. Then when I force quit the app it brings the messages back up.

Small clarification: do you mean the first time you click into any given conversation?

So to see if I can retell the story -- please say whether I've gotten this right:
* You open up the app.
* You tap on some PM conversation (like in the screenshot), or stream, etc. -- one you haven't looked at in the app before.
* It gives you the loading animation shown in the screenshot.... and stays that way for a long time.
  * I guess you didn't actually say the last part. :slightly_smiling_face: The loading animation is normal if it doesn't yet have all of the messages... but it shouldn't take long to get them, and then it should get replaced by the actual messages. How long did the loading animation continue before you gave up: a second or two, ten seconds, longer?
* You force-quit the app, and relaunch it.
* You tap on the same PM conversation or stream as before.
* This time, you get the messages.

**Comment by gnprice** [comment] 2019-10-21 18:17
> When the messages are displayed I can not get new messages until I quit the app again.

Oh and I almost forgot this part, which is a different and also quite bad symptom. So if I understand the story right -- again, please say whether I've correctly understood:
* [... The steps above, leading to ...]
* This time, you get the messages.
* But: then the other person / another person in the conversation sends a new message...
* and it doesn't show up.
* You force-quit the app, and relaunch it again.
* You tap on the same PM conversation or stream as before.
* Now that new message appears, along with the previous messages.

**Comment by jphilipsen05** [comment] 2019-10-21 18:23
Your story outline is correct. I have waited minutes to get the message to come up. I had it open for 10 minutes before I finally decided to stop seeing if it would come up. 

So yes your story and actions are correct. The only part I would add in your second list of points is:

* You force-quite the app, and relaunch it again
* You tap on the same PM conversation or stream as before
* Not that new message appears, along with the previoius messages
    * on occasion I have to force quit again because it shows the loading screen in the screen shot provided. This part is 50/50 on showing the conversation or loading page.

**Comment by gnprice** [comment] 2019-10-21 18:30
> I have waited minutes to get the message to come up. I had it open for 10 minutes before I finally decided to stop seeing if it would come up.

Cool -- that is very thorough, then :slightly_smiling_face: and definitely helps narrow the possibilities for debugging.

> Also I can look on my iPhone and it is instant and works as expected.

Hmm good to know.

FWIW I tried this on an iPhone XR running iOS 13 -- logged out to clear the data, then logged in, and went to a stream and the messages loaded promptly. Also went to a PM conversation and ditto. But it is good to confirm that it works *for you* on an iPhone -- that makes it less likely that it's a difference between your server, user, etc. and mine, and more likely that the different OS is involved.

(On the iPhone where it works properly for you, is it running iOS 13?)

I'll see about trying this on iPadOS.

**Comment by gnprice** [comment] 2019-10-21 18:36
> I'll see about trying this on iPadOS.

Hmm -- I got out an iPad mini 4 running iPadOS 13.1.2 (17A860), and the issue doesn't reproduce for me: messages load promptly as usual, even after logging into an account I hadn't used there before (so it's always the first time I'm looking at a given conversation.)


> two servers I'm working off of and both have the same issue. They are cloud hosted through zulipchat.com

Cool; that's quite helpful information too. Narrows the set of variables involved for debugging.

**Comment by gnprice** [comment] 2019-10-21 18:45
Still a mystery what the cause is, but given that it didn't reproduce on my iPad it seems less likely it's related to iPadOS (and more to some unknown other variable involved :-/ ). I've edited the title.

**Comment by gnprice** [comment] 2019-10-21 18:56
Also just to further narrow the variables involved: I went and re-attempted the repro on that same iPadOS device, this time with an org on zulipchat.com. (Previous testing was with a different service, chat.zulip.org.) Still didn't repro -- messages loaded promptly as usual.

**Comment by jphilipsen05** [comment] 2019-10-21 19:01
So I noticed that your version of iPadOS was different then mine so I updated to 13.1.3 (17A878). That seemed to take out the loading issue so I don't have to force quit to see the messages anymore. Now the only issue is as follows. 

* Open pm or stream
* read messages
* Send or receive new message
* message does not show up
* have to go out of the converstaion and then back in and they are the new messges that are sent/received now show up. 

So it appears the loading issues was in the earlier version of iPadOS 13.1 (17A844). However it seems to still be an issue that messages do not load in real time whil the chat window is up. However when I do get the message from someone I do get a 1 new message notification at the top, but no message at the bottom that reflects the notification.

It is better with the update, but not as snappy as the phone still. 

thanks for looking into this!

![Screenshot 2019-10-21 at 11 56 13 AM](https://user-images.githubusercontent.com/10887427/67234705-757cd680-f3fa-11e9-897e-838c4c7a4bc8.png)

**Comment by gnprice** [comment] 2019-10-21 20:10
> So I noticed that your version of iPadOS was different then mine so I updated to 13.1.3 (17A878). That seemed to take out the loading issue so I don't have to force quit to see the messages anymore. [...] So it appears the loading issues was in the earlier version of iPadOS 13.1 (17A844).

Huh! Good to know, then -- and glad that fixed it. Glad also that you mentioned the exact version, which reminded me to do the same :slightly_smiling_face: and made that difference apparent.

I'll look specifically at repro'ing the other symptom, then, where new messages aren't appearing.

**Comment by gnprice** [comment] 2019-10-21 20:23
> I'll look specifically at repro'ing the other symptom, then, where new messages aren't appearing.

Tried this one, and it works correctly for me -- the issue didn't reproduce. This was on the same iPad mini 4, now running iPadOS 13.1.3 (17A878) (I'd updated it after this morning's experiments), using zulipchat.com.

What version of the app are you running? I tried both 26.9.132 which is the current production release, and 26.11.134 which is the current beta.

**Comment by jphilipsen05** [comment] 2019-10-21 20:30
I am currently on v26.11.134. 

I just deleted it and downloaded the one from the app store which is v26.9.132

The loading page came back, and I still can't see the messages I send. When I do send the message though it comes up immediately on my other clients. I just still can't see it in the iPad app. I also only loaded one of the two zulip servers to make sure it wasn't something with the multiple servers effecting it. 

So after going back to 26.9.132 I am back to the same symptoms as before I upgraded my iPad.

**Comment by juddflamm** [comment] 2019-11-05 22:36
I have the exact same problem.  All of it exactly.  
![3880A100-80B3-4D5A-A735-BAAF7E0D47F4](https://user-images.githubusercontent.com/599981/68252157-f4b8ff80-ffe1-11e9-9299-5794bccaf7bb.jpeg)

PLEASE help!  I really need this bug fixed so that I can use Zulip.

**Comment by gnprice** [comment] 2019-11-06 23:29
Thanks @juddflamm for the additional report! That is fascinating that it's also on an iPad... given that we have many more people using Zulip on an iPhone than an iPad and we haven't yet heard of this issue happening there, that certainly adds some evidence that it's specific to iPads.

From your helpful screenshot I see you're on an iPad Pro, 3rd gen (i.e. 2018), 12.9". That contrasts with my iPad mini 4 where I was unable to reproduce the issue -- it'd be odd for this issue to somehow depend on the specific physical device model, but who knows. @jphilipsen05 , what model of iPad are you using?

**Comment by gnprice** [comment] 2019-11-07 00:10
OK, and I've now reproduced the issue! I used the iOS simulator, simulating the same model of iPad Pro as that last report.

More investigation to do, but that gives us a very nice start.

**Comment by gnprice** [comment] 2019-11-07 01:20
Detailed debugging in [a chat thread](https://chat.zulip.org/#narrow/stream/48-mobile/topic/messages.20don't.20load.2C.20on.20ipad/near/796152). Things learned so far:
* Simulated devices where the issue reproduces:
  * iPad Pro (12.9-inch) (3rd generation)
  * iPad Air (3rd generation)
  * iPad (7th generation)
  * (All of these are the latest of their respective lines.)
* Simulated devices where it doesn't:
  * iPad mini 4 -- i.e. the same as my physical device where it didn't
  * iPad mini (5th generation) -- interesting because that's a 2019 model, the newest of its line just like the ones where it did. And even has an A12 chip just like the iPad Air (3rd gen), and unlike the A10 in the iPad (7th gen).
  * (All simulated devices were running iOS 13.2 (17B84); the latest version, same as @juddflamm's real device.)

* The issue is probably in our communication with the webview where we show the message list, and not in our communication with the server or maintaining our local data-store.
  * In particular, when you send a message we normally show it in the message list immediately (a "local echo"), before hearing from the server. In an issue like #3567 where the problem really is in our communication with the server, the symptom is that that local-echo version hangs out indefinitely, complete with a little spinner -- not that the message doesn't show up.
  * If, for some reason, when we try to pass updates to the code inside the webview we always fail, that'd explain the symptoms exactly.
  * This is also an area where it makes perfect sense that an issue would interact with the OS version... and it's still a little puzzling that it depends on the *device model*, but it's not a huge surprise if Apple has some model-specific ~~hacks~~conditionals somewhere in the browser and/or `WKWebView` implementation.

**Comment by gnprice** [comment] 2019-11-07 01:26
Likely relevant is our #3572 , which is about the mechanism we use to pass updates to the code inside the webview:

> ## Stop using `postMessage` on WebView component
>
> This method is extremely useful, which is why we use it -- but it isn't documented, and the component's maintainer has a dim view of it. That makes it perilous to keep using; it's already suffered one breaking change -- apparently by accident! (see [fade1d3](https://github.com/zulip/zulip-mobile/commit/fade1d3e6e7ed547ef88fa97c1ad658c758150d6) and #3564 ) -- between versions ^4 and ^5.
> 
> Fortunately it's really just a thin wrapper around the equivalent of `injectJavascript`. So we can implement something just like that wrapper, and switch to using that.

I think the next debugging step will likely look a lot like a simple version of the said wrapper. So the fix may involve going ahead and switching to that wrapper, i.e. resolving #3572.

Done with detailed investigation for the day, but that's the direction I expect to pick up next.

**Comment by jphilipsen05** [comment] 2019-11-07 01:40
> Thanks @juddflamm for the additional report! That is fascinating that it's also on an iPad... given that we have many more people using Zulip on an iPhone than an iPad and we haven't yet heard of this issue happening there, that certainly adds some evidence that it's specific to iPads.
> 
> From your helpful screenshot I see you're on an iPad Pro, 3rd gen (i.e. 2018), 12.9". That contrasts with my iPad mini 4 where I was unable to reproduce the issue -- it'd be odd for this issue to somehow depend on the specific physical device model, but who knows. @jphilipsen05 , what model of iPad are you using?

I’m on an iPad Pro 3rd gen also.

**Closed** 2019-11-07 23:45 UTC
Labels: P1 high-priority, a-iOS, a-message list

**Comment by gnprice** [comment] 2019-11-08 00:16
And we have a fix! Details in commit f34c98c4d, which also appears in this issue thread just above here.

In short, the difference that triggered the issue turns out to be that on certain models of iPad, the user-agent string now contains no mention at all of iPad or iOS -- instead, every part of it is verbatim something you'll find on a Mac desktop. Reportedly this is intended as a way of getting websites to give the device their desktop version rather than a mobile version, which is understandable. That also explains why it *doesn't* happen on the iPad mini, even the 2019 model with a fully-updated OS.

In our case, though, this code never runs on desktop browsers in the first place, and the only platform variation we care about is between iOS and Android. So we'd had the following line:
```
const platformOS = window.navigator.userAgent.match(/iPhone|iPad|iPod/) ? 'ios' : 'android';
```
And we use that flag in one place, which is to deal with exactly the `postMessage` mechanism [I mentioned above](https://github.com/zulip/zulip-mobile/issues/3657#issuecomment-550577576): that library dispatches the events on the `window` object on one platform and `document` on the other, and so we need to know which platform we're on in order to adapt.

The fix is just a couple of lines, and drops any mention of the user-agent in favor of getting the iOS-vs-Android flag injected from the RN environment -- which is a closer match anyway to the variation we're using the flag to compensate for.

I'll make a release with this fix shortly, and I expect to send it out for all users today. If all goes smoothly, it will most likely reach the App Store tomorrow morning.

**Comment by gnprice** [comment] 2019-11-08 02:05
> I'll make a release with this fix shortly, and I expect to send it out for all users today. If all goes smoothly, it will most likely reach the App Store tomorrow morning.

Sent.

Thanks again @jphilipsen05 and @juddflamm for reporting this issue! The details you both provided were very helpful in tracking it down.

**Comment by gnprice** [comment] 2019-11-08 20:27
OK, and version 26.14.137 is out to the App Store! That has yesterday's fix for this issue.

@jphilipsen05 @juddflamm Please update and try it out, and let us know if that resolves it for you. Thanks again for the reports!

**Comment by jphilipsen05** [comment] 2019-11-08 21:54
@gnprice 

Thank you so much for getting that fixed. I updated my app on the iPad and I am able to see conversations, reply to them and get responses without re-loading the app now. 

Thanks!
