### ISSUE TITLE
Support attaching video

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#2939] opened 2018-09-05 05:02 UTC
There doesn't seem to be a way to attach a video.

This probably belongs inside the image-picker flow -- just enter the flow the same way you'd attach a still photo, and find the video in the camera roll there. If you try that in the current app, any videos you have just don't appear in the picker.

This is probably a natural follow-on to #2887 . That PR switches to a new library for the image picker, which has other nice features; this one might even come along for free.

**Comment by devZer0** [comment] 2019-02-14 00:41
yes please. major annoyance!

**Comment by maltokyo** [comment] 2019-09-20 12:18
Any updates on this, still can't attach a video to a post in Zulip.. (iOS)

**Comment by chrisbobbe** [comment] 2020-02-25 20:02
Closing as a duplicate of https://github.com/zulip/zulip-mobile/issues/3624, to focus conversation there, speeding up a solution.

**Closed by chrisbobbe** 2020-02-25 20:02 UTC
Labels: a-compose/send
