### ISSUE TITLE
webview: Inconsistencies on first render

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#3492] opened 2019-05-22 10:15 UTC
I have meant to address this for quite a long time. Putting this into an issue so it doesn't get lost or missed.

When we render the messages in `MessageList` we perform a necessary optimization. If we already have the messages cached we do render them immediately. This leads to two possible execution scenarios:
 * no message cache: render loading state, then send `content` event update
 * messages cached: render messages immediately

That may lead (indeed did lead in the past, and even currently) to potentially different behavior.
Looking at the code, I am concerned that anything in `handleUpdateEventContent` is not executed in the 'cache' case, for example, `appendAuthToImages`.

A possible solution is to always render the 'loading' state even if we have the messages and update them via a `content` event. Another would be a refactor to ensure better consistency.

**Comment by ishammahajan** [comment] 2019-05-22 11:27
I have noticed that the scroll position is often misplaced when opening streams which haven't been cached (not been opened before). More specifically, the scroll position seems to be on the top instead of the bottom of the list -- and consequently continues to load more messages since it thinks we scrolled to the top of the list.

This only reproduces on `yarn ios-min` though (not on android, emulator or device. Not on ios-max), so there might be a different issue at play here. However since it does reproduce only on uncached streams, it's worth putting up on here.
To reproduce:
1. Reinstall the app.
2. Try to open any stream (if it doesn't reproduce try opening another).

**Comment by ishammahajan** [comment] 2019-05-30 13:07
I haven't been able to reproduce the mentioned error successfully, even though I know that such a bug exists (effects are quite clear). The behavior seems to be rather erratic in that (as mentioned in the linked issue #M3492) `appendAuthToImages` fires at random times and in random conditions. 

* Fires 3 times when opening stream `GSoC` the first time.
* Fires 2 times when opening stream again.
* Fires 1 times the next.
* Doesn't fire at all next.

* Fires 10+ times in `mobile` once (which I assume is it loading content once).
* Fires never/2 times apparently randomly if stream is opened and closed repeatedly.
* Stops firing after a few opens and closes.

It would be great if someone familiar to this section of the code would provide an explanation if this is the expected behavior.

**Comment by borisyankov** [comment] 2019-05-30 14:46
Several months ago I have noticed exessive messages sent to the WebView. (as in more than the minimum necessary). I did mention that to @gnprice but since this was not causing an immediate bug we did not address this immediately.

This is a good area to research further, and also to learn about our WebView implementation.

There are different messages going in the WebView (now called 'update events') and coming from inside (the `js.js` file)

To monitor what is going in and out do add a console.log here:
https://github.com/zulip/zulip-mobile/blob/master/src/webview/MessageList.js#L136

What you are interested in is the `uevents` which is an array of one or more update events sent to the WebView.

For the other side of the communication add a console log here for `eventData`:
https://github.com/zulip/zulip-mobile/blob/master/src/webview/MessageList.js#L147

In most cases, you would want to ignore the 'ready' events which are only a handshake mechanism.
But don't completely ignore them, taking too long to agree that both sides are ready (RN and the WebView) could also be a sign of a problem.

**Comment by ishammahajan** [comment] 2019-06-05 09:04
Marked high priority because of multiple reports from users regarding this and related behaviour. Related [chat](https://chat.zulip.org/#narrow/stream/48-mobile/topic/start.20position.20when.20reading.20topics/near/746531). Also feel like it's irritating to the point of disdain for users who experience this often.

**Comment by gnprice** [comment] 2019-09-18 00:53
Thanks @ishammahajan for your investigation here!

The bug that the investigation is about is one we'd previously filed, as #3457. I'm going to close this thread to consolidate discussion there.

(This issue description is something different, but it's not a bug at all -- it describes an optimization we use, a guess that it might cause bugs, and a proposal to remove the optimization.)

**Closed by gnprice** 2019-09-18 00:53 UTC
Labels: P1 high-priority, a-message list, bug, zz-in progress
