### ISSUE TITLE
Avatars don't work on iOS 14, except in message list

### ISSUE THREAD

**Issue by titanous** [zulip/zulip-mobile#4365] opened 2020-12-30 02:32 UTC
The profile picture in the bottom tab bar is missing on local builds targeting the current version of iOS (see screenshot below). Additionally, the margin for the "home swipe bar" appears to be missing. I have tested this in a few different configurations, and here's what I found:

**Working**
- Release version (v27.157) from the App Store on an iPhone 12 with iOS 14.3
- master (05048c7007d30a6967333a3354f38c3ece68b3e8) built with Xcode 12.3 running in Simulator 13.7

**Broken**
- master built with Xcode 12.3 on an iPhone 12 with iOS 14.3
- master built with Xcode 12.3 running in Simulator 14.3
- master built with Xcode 12.3 running in Simulator 14.0
- v27.157 built with Xcode 12.3 running in Simulator 14.3

![Simulator Screen Shot - iPhone 12 - 2020-12-29 at 21 29 32](https://user-images.githubusercontent.com/13026/103326172-17e01300-4a1d-11eb-8c8e-094d0e9d14e7.png)

**Comment by chrisbobbe** [comment] 2020-12-30 03:16
Thanks for the detailed report, @titanous!

@gnprice, you mentioned [here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.60Immutable.2EMap.60.20performance.20for.20.60state.2Enarrows.60/near/1066833) the possibility of upgrading your test device's iOS version to 14. Did you end up doing that, or would it be best to keep it on its current version while plenty of people are still using that version? 🙂 (The latter has been my strategy for my iPhone so far.)

**Comment by gnprice** [comment] 2020-12-30 21:44
Thanks @titanous for the detailed report!

I just tried this in an iOS 14 test device, and it's working. That's:
* v27.157 from the App Store (well, TestFlight) on an iPhone XR with iOS 14.2

I see the profile picture there, and there's a margin below those five bottom icons.

One other variable which could affect this behavior is the type of avatar -- Zulip avatars can be hosted in a few different ways and places, and we've had bugs in the past which affected one or another type differently. In particular there's:
* A Gravatar, the default for a new user;
* An avatar the user uploaded, and which the Zulip server hosts locally (as chat.zulip.org and most other Zulip servers do);
* An avatar the user uploaded, and which the Zulip server stores in S3 and serves a redirect to there (as zulipchat.com does);
* An avatar that's ultimately one of the above, but where the Zulip server doesn't tell the client the URL up front, to save data on startup (significant when there's tons of inactive users, as on chat.zulip.org); this is new since v27.157, and only applies to users that have been inactive for weeks, which probably means it can't be involved for your own avatar.

I just tried the first two of these cases, and both worked.

Studying the set of configurations you tested:
* From the results on master in the simulator, it seems like something changed with iOS 14 that broke this.
* Then there's also the peculiar result that it works fine on v27.157 from the App Store, on a physical device, but breaks with the version you built from source at the same version, in the simulator. That is puzzling.

One test that would help narrow things down is to try it built from source at v27.157, but on the same physical device where the version from the App Store works. That will isolate whether it's the source vs. App Store, or physical vs. simulated device, that's making that difference. (Either of which would be puzzling and call for further investigation.)

> Additionally, the margin for the "home swipe bar" appears to be missing.

This sounds like an unrelated bug. Does it have the exact same pattern of working vs. not working (in those configurations you tested) as the missing-avatar bug? That'd be very interesting, just because it sounds so unrelated.

On its own, that symptom sounds like a case of #3066, which is an old bug that I have to admit I'm a bit embarrassed we haven't fixed yet.

**Comment by titanous** [comment] 2020-12-30 22:38
I saw the same thing for both of these variants:

- A Gravatar (in this case one of the random defaults)
- An avatar the user uploaded, and which the Zulip server hosts locally (testing on chat.zulip.org)

>One test that would help narrow things down is to try it built from source at v27.157, but on the same physical device where the version from the App Store works. That will isolate whether it's the source vs. App Store, or physical vs. simulated device, that's making that difference.

I did this test, and v27.157 built locally is broken on the same physical device where the App Store version is working.

I wonder if perhaps the App Store version was built against an older SDK version or with an older version of Xcode and so there's a compatibility layer that's being inserted?

> This sounds like an unrelated bug. Does it have the exact same pattern of working vs. not working (in those configurations you tested) as the missing-avatar bug? That'd be very interesting, just because it sounds so unrelated.

Indeed, after further testing, it is an unrelated bug. It only reproduces in the simulator for the 12/12 Pro/12 Pro Max and on my physical 12. The simulator 12 mini, and various models of the 11 have the correct margin. This is another case where the App Store version has the correct margin on my physical 12, but all local builds are broken.

**Comment by gnprice** [comment] 2020-12-30 23:51
> I did this test, and v27.157 built locally is broken on the same physical device where the App Store version is working.

Fascinating.


> I wonder if perhaps the App Store version was built against an older SDK version or with an older version of Xcode and so there's a compatibility layer that's being inserted?

Yeah, quite plausible.

On the machine I use for App Store builds, I have:
```
$ xcodebuild -version
Xcode 11.7
Build version 11E801a
```
so that's consistent with that theory. (I believe I haven't upgraded Xcode since building the v27.157 release; certainly I haven't downgraded it.)

I guess the next step is I should see if I can reproduce with that Xcode 11.7.

**Comment by gnprice** [comment] 2020-12-30 23:58
> Indeed, after further testing, it is an unrelated bug.

Cool. Filed that one as #4369.

**Comment by gnprice** [comment] 2020-12-31 01:30
> I guess the next step is I should see if I can reproduce with that Xcode 11.7.

I think the answer is... that I can't run that test! When I try to run the app from source on that device, I get an error saying "The current device configuration is unsupported. This iPhone XR is running iOS 14.3 (18C66), which is not supported by Xcode 11.7. To run on this device, please update to a version of Xcode that supports iOS 14.3."

Awkward because it appears that once I upgrade to Xcode 12, the next release I build will bring this bug to all users with affected devices... so I'd like to stay on Xcode 11 until this issue is resolved. (I only have the one Mac.)

I just took a look through the [iOS 14 release notes](https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-14-release-notes), and didn't find any change there that I could recognize as likely to be related to this issue.

I think the next step is to take a configuration where it's broken, and do some debugging there. Some debugging questions that might be helpful to answer to narrow things down:
* Are avatars showing up just fine in other places in the app? E.g.:
  * in the list of PM conversations (the "people" icon in that main bottom nav)
  * the giant version of your own avatar, at the "profile" screen that that lower-right icon leads to
    * Or is that button not even working? I'd guess that it works and just isn't rendering its image.
  * in the message list when you go look at some messages
* Is the `OwnAvatar` component (which supplies the avatar in that spot in the main bottom nav) winding up with the right avatar URL?
* If so, is something going wrong in the request to fetch that image?
  * This might be easiest to debug from the server side: using an uploaded avatar on a [development Zulip server](https://github.com/zulip/zulip-mobile/blob/master/docs/howto/dev-server.md), or another server where you can inspect the server logs.

**Comment by gnprice** [comment] 2020-12-31 01:32
> (I believe I haven't upgraded Xcode since building the v27.157 release; certainly I haven't downgraded it.)

Oh, and a correction on this part: I actually did upgrade Xcode ([chat thread](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.60Immutable.2EMap.60.20performance.20for.20.60state.2Enarrows.60/near/1066785)) the week after building that release. Previously it was Xcode 11.3.

**Comment by titanous** [comment] 2020-12-31 02:05
> * Are avatars showing up just fine in other places in the app? E.g.:
>   * in the list of PM conversations (the "people" icon in that main bottom nav)

Missing here.

> * the giant version of your own avatar, at the "profile" screen that that lower-right icon leads to

Missing here.

> * Or is that button not even working? I'd guess that it works and just isn't rendering its image.

The button working.

>   * in the message list when you go look at some messages

Works here.

I'll dig further on this after I put together the PR for another fix I'm working on.

**Comment by gnprice** [comment] 2020-12-31 02:52
> I'll dig further on this after I put together the PR for another fix I'm working on.

Sounds great!

Interpreting a bit that pattern of observations:
* it's failing everywhere that we try to show an avatar directly from the React Native part of the app;
* it's working where the avatar instead appears inside the webview for the message list.

In the first category, all those spots in the app ultimately use our `UserAvatar` component; and that just uses RN's built-in `ImageBackground` component, passing it an appropriate source URL for the avatar image.

In the second category, the RN code that's putting together the HTML supplies an avatar URL (see e.g. `messageAsHtml.js`); and then inside the webview, some other code goes and rewrites the `src` attributes, when they point to specific URL routes on the Zulip server, to include the user's API key in the query part.

See also #4367 -- that edits `UserAvatar` to fix a bug with some very similar symptoms. But that seems to be a different bug -- it was happening on iOS 13 and on Android, and on the other hand only for certain types of avatars (the fourth of the four categories I mentioned at https://github.com/zulip/zulip-mobile/issues/4365#issuecomment-752768167 .)

At this point it seems possible that the bug we're looking at is in RN, in the implementation of `ImageBackground`. Certainly it looks likely that further debugging will soon lead into doing some debugging in that implementation.

**Comment by titanous** [comment] 2021-01-01 01:45
This is facebook/react-native#29279 and facebook/react-native#29215, fixed in https://github.com/facebook/react-native/commit/123423c2a9258c9af25ca9bffe1f10c42a176bf3 (v0.64) and https://github.com/facebook/react-native/commit/b6ded7261544c703e82e8dbfa442dad4b201d428 (v0.63.2).

**Comment by titanous** [comment] 2021-01-01 01:46
This is blocked by #4245.

**Comment by gnprice** [comment] 2021-01-04 22:38
@titanous Great, thanks for tracking that down!

This makes a good reason for us to take the time soon to complete that RN upgrade. As you can see on #4245, Chris has marked it now as a priority issue.

**Comment by gnprice** [comment] 2021-01-26 06:48
Hmm, well -- we landed that RN upgrade last week (to v0.63.4), which we expected would fix this. But with #4431, we have a report of what sound like the same symptoms still appearing.

@titanous Would you try this again with a current version from master, and confirm whether it still reproduces for you?

If it does, then I wonder if something went wrong with that bugfix in RN upstream, or if we're seeing some other bug that happens to have overlapping symptoms.

**Comment by gnprice** [comment] 2021-01-26 06:49
Also reopening this issue -- given that report, seems safest to regard it as open until we have some confirmation that the fix seemed to work :slightly_smiling_face:

**Comment by chrisbobbe** [comment] 2021-04-14 01:57
> seems safest to regard it as open until we have some confirmation that the fix seemed to work 🙂

We may have it. @Gautam-Arora24, the author of #4431, said,

> I think building the app from scratch on iPhone solved my problem.

**Closed** 2021-04-15 17:22 UTC
Labels: P1 high-priority, a-avatar, a-iOS
