### ISSUE TITLE
"No connection" banner when connected fine, on VPN

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3602] opened 2019-09-03 17:20 UTC
A user reports [in chat](https://chat.zulip.org/#narrow/stream/48-mobile/topic/android.20.22No.20internet.20connection.22/near/784471):
> I decided to upgrade my phone from Android 7 to Android 9. Zulip connected without a problem, but is now showing a red banner on top of the screen "No internet connection". Funny thing is that everything is working, messages can be fetched/delivered, just the banner is annoying.
> An important addition - this message only appears when VPN is on (android 'Always-on VPN', 'Block connections without VPN' enabled). Somehow somewhere a connection is dropped, which makes Zulip think that there is no internet, while the main API (chat.zulip.org, for example) is responding just fine.

Quick investigation I did just now:

We decide whether to show that banner based on the device's reported network state. (This is in `src/boot/AppEventHandlers.js`, dispatching an `appOnline` action which controls `state.session.isOnline`.) It comes to us like so:
https://github.com/react-native-community/react-native-netinfo#netinfostatetype
and we say "No Internet connection" if the connection type is none or unknown.

There might be a better way for us to use that API.

Also I guess if we are successfully hearing from the actual server, we should probably infer that the network is doing fine after all :)

**Comment by gnprice** [comment] 2019-09-23 18:29
A user reported this in a Play Store review, in the following terms:
> shows "offline" bar whenever vpn is on.

**Comment by ray-kraesig** [comment] 2019-10-19 00:57
Well, this is baffling.

* Since our commit b909c0a22, we're on 3.2.1 of react-native-netinfo... and since its 3.1.0 release, that API is documented to return `'vpn'` when the Android device is connected to a VPN. I'd _like_ to close this as "fixed in the current version", but...

* That commit would have been pushed out as part of 26.5.128, which went to a full release on the Play Store on or around 2019-08-26. However, the original report was dated 2019-09-02 — and the report in the Play Store was not only dated 2019-09-23, but is specifically associated with 26.5.128.

* More confusingly, testing (against `master` on an emulator) has so far failed to reproduce the symptoms; the red banner does not appear when a VPN connection is available... but logs of the output of `...-netinfo` are reporting that a `wifi` or `cellular` connection is available, not a `vpn`.

**Comment by ray-kraesig** [comment] 2019-10-22 20:51
Update: it's much less baffling now.

* The NetInfo API has been updated into something subtly incompatible. The old behavior – which includes not providing `'vpn'` – is preserved if you call it the old way.

* Using the old API actually emits a message to the React console: 
    > Warning: RNCNetInfo - You are using the deprecated API. It will still work, but you must upgrade to the new API to receive the new features. The old API will be removed in the future

  ... which seems to have been ignored or missed, back when it was first applied. :disappointed:

I have a probable fix; it's on hold, pending an Android 9.0 device suitable for testing, since I haven't yet been able to reproduce the original bug on the emulator or on non-Pie devices.

**Comment by gnprice** [comment] 2019-10-25 20:46
> * Using the old API actually emits a message to the React console:
>   > Warning: RNCNetInfo - You are using the deprecated API. It will still work, but you must upgrade to the new API to receive the new features. The old API will be removed in the future
>   
>   
>   ... which seems to have been ignored or missed, back when it was first applied. disappointed

Dang. Thanks for tracking this down!

Looks like we made the change in #3587, motivated by #3568.

**Closed** 2019-10-29 18:09 UTC
