### ISSUE TITLE
question: Emoji Compatibility

### ISSUE THREAD

**Issue by ro-i** [zulip/zulip-mobile#4682] opened 2021-04-20 18:45 UTC
Hi! :)
I've received feedback from a user who is using an older version of Android (6.0 in that case). He reported that some emojis do not work (e.g. :shrug: , which has been added in Unicode 9.0 - see https://emojipedia.org/person-shrugging/).
There seems to be a way to provide older Android versions with newer emojis: https://developer.android.com/guide/topics/ui/look-and-feel/emoji-compat
Maybe you want to consider using this library? (I'm not familiar with Android development, I'm just forwarding this suggestion...)
Have a nice day! :)

**Comment by WesleyAC** [comment] 2021-04-21 15:35
Thanks for reporting this! This is something we'd like to fix — we actually talked about using that library in #3885, but decided on an alternative solution. At the time, we were blocked on doing that, but now that we've upgraded our version of React Native, there's a clear path towards this.

I'm going to go ahead and mark this as a dupe of #3885, you can follow along there for updates :)

**Closed by WesleyAC** 2021-04-21 15:35 UTC
