### ISSUE TITLE
Android: Make headers to float/stick on top.

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#510] opened 2017-04-13 21:09 UTC
![ezgif com-crop 6](https://cloud.githubusercontent.com/assets/18511177/25024380/5d91644c-20bb-11e7-9c9a-d3a9f76c4adc.gif)

**Comment by borisyankov** [comment] 2017-04-14 20:38
Hmmm, how did you achieve this?
It is working fine for me.

**Comment by vishwesh3** [comment] 2017-04-15 00:10
normal run on Android.

**Comment by divs4debu** [comment] 2017-04-19 03:17
@vishwesh3 @borisyankov I searched little about it and found that this feature will be implemented in react-native 0.44 [https://github.com/facebook/react-native/issues/2700](url).
One solution can be changing the android specific code in android generated files and implement scroll listeners .

**Comment by borisyankov** [comment] 2017-04-19 15:53
Cool, thanks for finding it.
I wasn't even aware it is not yet supported. Rather good timing I must admit ;)
We can definitely wait till 0.44 which will release in 15-20 days.

Also, we will be investigating if we can replace the ScrollView for MessageList with the new SectionList.

**Comment by kunall17** [comment] 2017-05-05 14:57
@vishwesh3 are you working on this one?

**Comment by borisyankov** [comment] 2017-05-05 15:06
I am not sure if this feature made it in RN 0.44
If not, we can not implement. If yes, the issue is auto-resolved when we upgrade to 0.44

Also, we might just use FlatList/SectionList for the MessageList soon.

**Comment by borisyankov** [comment] 2018-05-09 14:33
No longer relevant.

**Closed by borisyankov** 2018-05-09 14:33 UTC
