### ISSUE TITLE
Language translations incorrect

### ISSUE THREAD

**Issue by thejwzhang** [zulip/zulip-mobile#1481] opened 2017-12-01 07:24 UTC
I'm not completely proficient at Spanish, but when I switch to the Spanish language, there are words that are definitely either wrong or not translated. See the screenshot below. "Yesterday" is not translated, and the word "memsaje" should be "mensaje" for "message". (@YagoGG If you have time, simply change this line: https://github.com/zulip/zulip-mobile/blob/55ab0bf94e82d04eb708b1066ccc8b0fa99ca1e8/src/i18n/translations/messages_es.json#L62). 

Other issues (in the 2nd screenshot) are that "edited 2 days ago" is still in English. I understand that all the topics, channels, and names cannot and should not be translated but the system text should. 

Neither "Yesterday" nor "edited _ days ago" are marked for translation. "Yesterday" (as well as "Today") is found here: https://github.com/zulip/zulip-mobile/blob/55ab0bf94e82d04eb708b1066ccc8b0fa99ca1e8/src/utils/__tests__/date-test.js#L47-L53. "edited _ days ago" is found here: https://github.com/zulip/zulip-mobile/blob/55ab0bf94e82d04eb708b1066ccc8b0fa99ca1e8/src/message/MessageTags.js#L58

This same issues and others happen when I switch to other languages. For example, if I switch to Chinese (in the 3rd screenshot), the entire word "message" is still in English. In this screenshot, I'm holding down on the screen while taking the screenshot to demonstrate that I'm in the Chinese language yet the word "Message" (partly hidden by the left slide-in) is displayed in English. From the mentors I learned that these types of translations (where one language gets translated and another isn't) are due to individual languages not having phrases in its file (https://github.com/zulip/zulip-mobile/tree/master/src/i18n/translations) for certain English phrases.

To get to these issues, simply log in to Zulip, click languages, and select any language. Then go back into the app and look for the words that are not translated or translated incorrectly.

![screenshot1](https://user-images.githubusercontent.com/12479968/33472030-271ac974-d625-11e7-8c5b-996c4b1ae61d.png)

![screenshot2](https://user-images.githubusercontent.com/12479968/33472049-3e7c0984-d625-11e7-8708-62b87d0aaf1f.png)

![screenshot3](https://user-images.githubusercontent.com/12479968/33472062-5044da7e-d625-11e7-9a92-860dd46aa68d.png)

**Comment by roberthoenig** [comment] 2017-12-02 09:02
Thank you for the detailed report, @thejwzhang! A couple things:

* I don't consider "memsaje" -> "mensaje" an actual a bug in the software, but it's still a nice find! Mentioning @YagoGG, if he has time to update this :)

* if Spanish word for "message" is translated, but the Chinese word isn't, it means that the word is correctly tagged, but simply has not been translated yet. That's annoying, but not a bug :)

* "Yesterday" and "edited x days ago" not being translated are good finds. It is quite likely that these have not been tagged for translation, even if they should be. However, it is also possible that they simply have not been translated yet. Can you check if these strings have been marked for translation (should check in the zulip-mobile repo)? If not, you should add that information to the issue description, preferably with a link to the source line, and we can approve this :)

**Comment by YagoGG** [comment] 2017-12-02 12:23
As Robert said, thank you for such a nice report @thejwzhang!

- I have just fixed the "memsaje" typo, good catch! It should appear correctly in the next release of the app.
- Regarding the strings that aren't translated, it's mostly what @roberthoenig mentioned: due to some technical difficulties, about a 30% of the mobile app strings aren't translated (I'm only talking about Spanish, don't know about other languages). The best thing you can do in those cases is to check [the source](https://github.com/zulip/zulip-mobile/) and make sure that they have been tagged for translation.

**Comment by borisyankov** [comment] 2017-12-02 12:52
Thanks, @roberthoenig @YagoGG
Apart from missing translations and occasional incorrect translations, there are two other issues that we can do more on the development side. So pinging @jainkuniya and @kunall17 to help too ;)

The first is easy: just missed strings to translate. I think there aren't many but will be great to find and fix them.

The second is more tricky: the stuff that is 'calculated'. For example, the '2 days ago' is calculated by an external function and is not directly translatable.

**Comment by borisyankov** [comment] 2018-05-30 10:01
Closing as no longer relevant.

**Closed by borisyankov** 2018-05-30 10:01 UTC
Labels: bug
