### ISSUE TITLE
Realm emoji don't work in autocomplete or reactions

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#2846] opened 2018-07-28 00:39 UTC
If you're composing a message and start typing an emoji's name, like `:smi`, we show a nice autocomplete popup with possibilities like `:smile:`.

If the emoji you have in mind is a realm emoji, though (or a Zulip extra emoji -- i.e. `:zulip:`, though in principle there could be more in the future), it won't appear. Also, if people have reacted to a message with a realm emoji or a/the Zulip extra emoji, those won't show up right (that's #2129, though I think we've since patched it up so at least we don't literally say "undefined".)

Happily both kinds work in the one most important place, which is rendering a message. But these other places are important too.

I think the basic root cause here is that our code for passing around the information about realm emoji is very confusing and it's hard to figure out what value is supposed to be what -- e.g. whether a prop called `realmEmoji` is supposed to be an object representing one emoji, or a map indexed by emoji code / id, or a map indexed by name. So the main step will be to fix that, which means refactoring and renaming a lot of pieces, adding type annotations where we don't already have them, and adding jsdoc in a few places for things to know that can't be expressed in the name and the types.

(I have some more specific thoughts on what a solution will look like, which I'll try to write up in a bit.)

Once that's done, I think the bugs as seen by the user will be straightforward to fix.

---
For cross-reference:

There's some work on this in the latter part of PR #2775, and in #2307 in commits a5a24a81e "realmEmoji: Fix realm emojis are not appearing in autocomplete" and c24432ed5 "reactions: Fix clicking on reactions doesn't work".

In addition to #2129, this may be the cause of #2806.

**Comment by agzuniverse** [comment] 2018-07-29 16:22
@zulipbot claim

**Comment by jainkuniya** [comment] 2018-07-30 04:33
@agzuniverse on which part are you planning to work 🤔. There is already PR for this #2307

**Comment by agzuniverse** [comment] 2018-07-30 14:20
Modifying the realm emoji selectors as I did in #2775 fixes the problem of realm emoji not showing up the app at all. This is the simplest fix to this problem as all the code in the app is already set up to work with a specific structure of the `relmEmoji` object, it's just that this is not the structure returned by the selector right now.

The commit with this modification was not merged in that PR, so I'll be doing that in a clearer way and opening a PR for that.

**Comment by 0rmi** [comment] 2018-11-12 19:18
@agzuniverse @gnprice reading through these commits, do I assume correctly that the issue is fixed in agzunierse's fork and I could get working realm emotes already by building his code?

**Closed** 2018-11-28 03:04 UTC
Labels: P1 high-priority, in progress
