### ISSUE TITLE
Android Notifications Don't Work If Installed by Google Play Store

### ISSUE THREAD

**Issue by adambirds** [zulip/zulip-mobile#4560] opened 2021-03-23 01:16 UTC
Push Notifications on Android Devices don't work if installed via Google Play Store. 

This has been tested rigorously all day as can be seen in - https://chat.zulip.org/#narrow/stream/48-mobile/topic/Push.20Notifications.20on.20Mobile.20.28Android.29

This has tested both with a self-hosted server and chat.zulip.org.

If the app (even the latest version) is installed by APK, then the notifications work fine, you can see devicetoken get registered in `/var/log/zulip/server.log` as you login for the first time on the mobile device.

If you download and install via Google Play, then the notifications don't work and you don't see the token get registered in `/var/log/zulip/server.log`

**Comment by chrisbobbe** [comment] 2021-03-24 01:25
Thanks so much for the report and debugging help, @adambirds! You know this already, but I've started a new topic [here](https://chat.zulip.org/#narrow/stream/48-mobile/topic/.60remoteNotificationsRegistered.60.20listener.20too.20late/near/1141501) with a suggested diagnosis.

**Comment by gnprice** [comment] 2021-03-30 01:14
It looks like we now have a diagnosis for this and a plan for a fix. Details in the chat threads linked above. I expect we'll have a new release out soon which fixes the issue.

Thanks again @adambirds for the report and debugging!

**Comment by chrisbobbe** [comment] 2021-03-30 16:57
We've confirmed that this is fixed by #4573, released in an Android-only beta v27.160; see discussion around [here](https://chat.zulip.org/#narrow/stream/48-mobile/topic/.60remoteNotificationsRegistered.60.20listener.20too.20late/near/1147594). So, closing! 🎉

**Closed by chrisbobbe** 2021-03-30 16:57 UTC
Labels: P0 critical, a-Android, a-notifications

**Comment by gnprice** [comment] 2021-03-30 19:36
And v27.160 is now out for all Android users!

If anyone's still having trouble with notifications after taking that upgrade, please do file a new issue -- we'd be glad to debug.

**Comment by easaw** [comment] 2021-03-30 21:51
"Stealing" my issue #4556  there @adambirds? 😂
