### ISSUE TITLE
Attached picture is posted before caption is typed

### ISSUE THREAD

**Issue by Be-ing** [zulip/zulip-mobile#3299] opened 2019-01-21 17:25 UTC
When attaching a picture to a post, the picture is posted in its own post before I can type a caption. I wanted to post the picture and caption in the same post, but someone else commented on the picture before seeing the context I provided with the text caption.

**Comment by armaanahluwalia** [comment] 2019-01-23 09:21
This will be addressed by #2887

**Comment by chrisbobbe** [comment] 2023-01-17 20:33
Thanks for the request! Closing as a duplicate of #4540, fixed in #5474.

**Closed by chrisbobbe** 2023-01-17 20:33 UTC
Labels: duplicate
