### ISSUE TITLE
Quote and reply feature like zulip's Web-app

### ISSUE THREAD

**Issue by abhi0504** [zulip/zulip-mobile#4504] opened 2021-03-01 19:14 UTC
There is a `quote and reply` feature in zulip's web app for each message which I think is very useful and must be present in our zulip's mobile app too 

https://user-images.githubusercontent.com/56453541/109546175-d8eb3e00-7aef-11eb-9db1-05c33f3b9da8.mp4

A kind of similar feature is available in our mobile-app but it seems to work differently on long press on any message a `messageActionSheet` opens and it has the `reply` option but it only opens that conversation and then on long press on any message `messageActionSheet` opens but there is no option of `reply`

https://user-images.githubusercontent.com/56453541/109546519-544cef80-7af0-11eb-8127-8f50fdedfd28.mp4

I think there must be an option like `quote and reply` or `reply`

@chrisbobbe and @gnprice please have a look over this issue and please give some suggestions I want to work on this issue

**Comment by abhi0504** [comment] 2021-03-08 07:27
working on this issue

**Comment by chrisbobbe** [comment] 2021-03-16 16:40
> working on this issue

Thanks, @abhi0504!

What are you considering as possible plans for implementing the feature? I see four other open issues in my [search for issues like this one](https://github.com/zulip/zulip-mobile/issues?q=is%3Aissue+is%3Aopen+quote+and+reply+). I expect they'll provide some helpful ideas. 🙂 In fact, this issue looks like a duplicate of #1975, so I'm closing this one.

One thing that stands out to me, from Greg's comment at https://github.com/zulip/zulip-mobile/issues/3436#issue-427855536, is that we might like to wait to start on #1975 until a first version of #3436 has been merged.

**Closed by chrisbobbe** 2021-03-16 16:40 UTC
