### ISSUE TITLE
"No Browser Found" when clicking on a link on LineageOS

### ISSUE THREAD

**Issue by foxyseta** [zulip/zulip-mobile#5795] opened 2023-11-20 22:15 UTC
I am sure I have a mobile browser installed. Other apps open links in a new browser instance just fine, too.

**Comment by gnprice** [comment] 2024-03-04 22:38
Thanks @foxyseta for the report! Sorry for the delayed reply.

We have an upcoming new Zulip mobile app which is now in beta (since December):
https://chat.zulip.org/#narrow/stream/2-general/topic/Flutter/near/1708728
Would you try that out and see if this issue reproduces there?

Because this app is now in maintenance mode as we're focusing on building out the new app, I think this issue is one that we're unfortunately not going to spend time diagnosing and fixing in the legacy app. But if it reproduces in the new app, then I'll definitely be interested in getting to the bottom of it there.

**Comment by foxyseta** [comment] 2024-03-04 23:18
I see. The legacy app was just one big nasty webview, if I remember correctly, so this is surely for the better. Good luck with the new one! I found the the Google Play links, but not the apks download page or the F-droid links for some reason. Is the new app exclusively available through that one proprietary platform?

**Comment by gnprice** [comment] 2024-03-05 00:48
Thanks! The legacy app isn't all *one* big webview — most of the UI is built in React Native, though probably most of one's time interacting with it is interacting with webviews. Specifically, when you're reading messages in the app, the list of messages is a webview. (Details [here](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Message.20List.20History/near/809351), from a few years ago, if you're curious.)

At this stage of the beta for the new app, we've been publishing the Android builds only through Google Play, partly because the beta is developing rapidly and we want to make sure people get updates to it. As we reach a stage where we're advertising it more widely, we'll definitely post the APKs directly too. (You're naturally also welcome to build the app yourself. Flutter itself is pretty lightweight to install and build with, but it does require an Android build setup and I recognize that's more of a pain if you don't already have one lying around.)

Meanwhile, in going through the tracker today, I also just came across a previous report of what may be the same issue: #5466. It has a reported workaround, so you might try that.

And after seeing that issue, I suspect that the bug you're running into will only apply when trying to open links with a browser in-app. You can change that setting to instead open in a separate browser app:
https://zulip.com/help/configure-how-links-open
and I expect that will work around this bug.

**Comment by foxyseta** [comment] 2024-03-09 04:30
Works great on the new app, thanks. You can close this issue, if you want to.

**Comment by gnprice** [comment] 2024-03-11 23:33
Glad to hear it — thanks for confirming.

I'll close this issue thread in order to consolidate on #5466, because I'm now pretty confident they're the same issue. I'll be leaving that one open because this is an ongoing bug in this app… it's just one that we plan to leave behind when we eventually replace this with the new app and archive this repo.

(If we were using the strategy where issues relating to all the different Zulip repos were tracked in a single repo's tracker, then I guess we'd mass-close all those left-behind issues as wontfix when we complete the migration. That strategy has pros and cons. But since we're not using that strategy, I expect we'll leave them as open issues in an archived repo.)

**Closed by gnprice** 2024-03-11 23:33 UTC
Labels: a-Android
