### ISSUE TITLE
Removing account from list doesn't stop notifications

### ISSUE THREAD

**Issue by overide** [zulip/zulip-mobile#3469] opened 2019-05-02 10:47 UTC
I've removed the previous organization couple of days ago but I'm still getting the push notifications from it. Check the screenshots below - 
![part-1](https://user-images.githubusercontent.com/19911594/57070622-a6a30680-6cf5-11e9-938d-5a1449a7ac68.jpeg)
![part-2](https://user-images.githubusercontent.com/19911594/57070627-a9056080-6cf5-11e9-9888-9b83b63fb907.jpeg)

**Comment by borisyankov** [comment] 2019-05-02 17:10
Thanks for reporting this. 
I have identified where the problem is and will work on a fix. (we are stopping notifications when you logout, but not when you delete an account)

**Comment by borisyankov** [comment] 2019-05-02 17:11
As a workaround before the fix is done and ships, you can add the account again and log out of it before deleting it.

**Comment by overide** [comment] 2019-05-04 09:54
> As a workaround before the fix is done and ships:
> 
> * the account again
> * log out of it
> * delete it again

Thanks for this @borisyankov

**Comment by chrisbobbe** [comment] 2020-08-26 08:04
IIUC, Boris was thinking of doing something like calling `tryStopNotifications` near where `removeAccount()` is dispatched. It looks like a fix of this kind hasn't landed. 

Another thing I just noticed: Whereas `tryStopNotifications()` is dispatched in `ProfileCard` alongside `logout()`, the other `logout()` dispatch sites do not dispatch `tryStopNotifications()`. Those dispatch sites are for unceremoniously kicking the user out if the server responds with an "Unauthorized" error. This inconsistency may be a symptom of the fuzzy shift in semantics Greg and I describe [here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Redux.20actions.20as.20.22news.22/near/987342).

**Comment by gnprice** [comment] 2021-08-04 21:39
A new report of this issue today:
https://chat.zulip.org/#narrow/stream/48-mobile/topic/receiving.20notifications.20in.20logged.20out.20realm/near/1243574

> doing something like calling `tryStopNotifications` near where `removeAccount()` is dispatched.

This fix should be pretty straightforward to do, and we should do it.

It's just a bit trickier than adding a dispatch of `tryStopNotifications`, because the latter is written to act on the active account.

Probably the right fix is:
* refactor `tryStopNotifications`, and its helper `innerTryStopNotifications`, a bit so that there's a version that takes an `Account` object;
* in `AccountPickScreen`, next to the `removeAccount` call, add a call to that new version of `tryStopNotifications`.

We should also fix this:

> Another thing I just noticed: Whereas `tryStopNotifications()` is dispatched in `ProfileCard` alongside `logout()`, the other `logout()` dispatch sites do not dispatch `tryStopNotifications()`. Those dispatch sites are for unceremoniously kicking the user out if the server responds with an "Unauthorized" error. So, such users will probably continue to receive notifications.

but that should probably be its own separate issue.

**Closed** 2022-12-07 18:48 UTC
Labels: help wanted, a-notifications, a-multi-org, P1 high-priority
