### ISSUE TITLE
Images not cached in WebView

### ISSUE THREAD

**Issue by armaanahluwalia** [zulip/zulip-mobile#3026] opened 2018-10-08 04:07 UTC
I did a bit of digging and it turns out we are re-rendering the WebView on any change to messages. This causes a re-request for all images within a thread anytime the state of messages is changed. This is expensive both in terms, of performance as well as bandwidth usage.  A thread with more than a few images will cause a lot of wasted data.

2 possible solutions I can think of are -
1) Do not re-render WebView on all changes to messages and instead update, append or remove messages as needed.
2) Enable proper cacheing in WebViews. As per my quick research this is not as easy as it sounds. Probably different for Android and iOS.

Tested on both iOS and android. New requests are made to the server on any change to messages.

Relevant discussion in this thread https://chat.zulip.org/#narrow/stream/48-mobile/topic/Excessive.20Rendering.20Bug

**Comment by gnprice** [comment] 2020-01-10 21:53
See also #3790. The issues are independent, but each one basically multiplies the impact of the other.

**Comment by gnprice** [comment] 2020-01-29 00:22
The original description is a bit loosely worded, which I found confusing when re-reading this today. Here's some clarification, based on rereading the (quite detailed) linked chat thread, and also the code.

We're not in fact having a new React `render()` call that affects the WebView, or re-creating the React `WebView` component, or anything like that. At least, AFAICT there's no sign of that in this report.

What does happen is that, inside the `WebView` that provides the message list, we replace the entire content of the `body` with an updated version. See `handleUpdateEventContent` in `js.js`.

This happens whenever a new message comes in that should appear in the current message list, or another change happens that affects one of the messages in the current message list. See `MessageList#shouldComponentUpdate`, and the `getUpdateEvents` function (in `webViewHandleUpdates.js`) which it invokes.

So far, everything I've described above is by design. Then the observation that makes this issue is that apparently the browser handles images very inefficiently in this case: it fetches all the same images again, rather than get them from cache.

Separately, it sure feels inefficient to be replacing the entire body when only one message has changed (which is the usual case). Maybe we should change that. That's solution 1 in the description above, because it'd also resolve this issue.

Separately separately, there could be bugs where we replace the `body` much more often, in cases where in fact nothing in it has changed at all. The linked chat thread started with a report of a bug of that form. We promptly fixed that, in commit 9fc769802. If there are cases now where that happens, we should file new issues for those and fix them too.

**Comment by chrisbobbe** [comment] 2020-01-30 01:29
> We're not in fact having a new React render() call that affects the WebView, or re-creating the React WebView component, or anything like that. At least, AFAICT there's no sign of that in this report.

Confirmed with logging. There are two initial React `render()`s (I'm not sure why) but not with updates to messages.

**Comment by chrisbobbe** [comment] 2020-01-31 03:00
> Enable proper cacheing in WebViews. As per my quick research this is not as easy as it sounds. Probably different for Android and iOS.

It appears that an improvement was made to this situation in fade1d3e6 (and [released](https://github.com/zulip/zulip-mobile/releases/tag/25.8.122) in July, 2019), when we upgraded from react-native-webview 2.0.0 to ^5.0.0, since [4.0.0](https://github.com/react-native-community/react-native-webview/releases/tag/v4.0.0) enabled caching in the WebView and turned it on by default. I did some manual testing on both iOS and Android and confirmed that the caching is actually happening — but there are still some important limitations.

First, this caching is only done per-WebView instance. It remains the case that new downloads will happen when the entire WebView component is unmounted and remounted. This happens frequently enough for it to be a concern, e.g., when switching between a stream and a topic. Larger commitments would be needed to address this.

Second, some of the images have sizes that are just way too large for our needs; one photo from the iOS simulator's media library was 13MB. Unfortunately, on Android, at least, there are sometimes failures to receive the entire file (we're not sure if this is a client- or server-side problem), and when it isn't received completely, it isn't cached. So there are indeed cases where small updates to the list of messages (reactions, new messages, edits, etc.) trigger fresh (and often failing) attempts to download large files.

Third, I only tested on chat.zulip.org, which seems to be exempt from a challenge to the ability to cache that's being addressed elsewhere. @timabbott can best explain this. 🙂

> Do not ~~re-render WebView~~ replace html body [my edit] on all changes to messages and instead update, append or remove messages as needed.

I'm opening this as https://github.com/zulip/zulip-mobile/issues/3851. It's become somewhat less urgent because of the react-native-webview update I described, but it would still be really nice to do. And, as Greg describes, there may still be lingering bugs where the entire body is replaced even when there are no changes.

Otherwise, @gnprice, what do you think about closing this issue, once we've started tracking the challenge Tim described?

**Comment by timabbott** [comment] 2020-01-31 20:26
The caching issue with the S3 backend is this: https://github.com/zulip/zulip/issues/13088

**Comment by gnprice** [comment] 2020-01-31 22:52
> Otherwise, @gnprice, what do you think about closing this issue, once we've started tracking the challenge Tim described today, and perhaps opening any other issues?

Sounds like a good plan! I've just filed #3853 as our counterpart of zulip/zulip#13088, and I think this broader issue can now be closed.

**Closed** 2020-01-31 22:55 UTC
Labels: a-message list

**Comment by chrisbobbe** [comment] 2020-02-01 09:28
> First, this caching is only done per-WebView instance. It remains the case that new downloads will happen when the entire WebView component is unmounted and remounted. This happens frequently enough for it to be a concern, e.g., when switching between a stream and a topic. Larger commitments would be needed to address this.

It appears that this has been reported; I can track investigations of sharing the cache between message lists there: https://github.com/zulip/zulip-mobile/issues/3180
