### ISSUE TITLE
Selfhosted: TLS error on only one group chat, only on Android

### ISSUE THREAD

**Issue by alexferro** [zulip/zulip-mobile#4337] opened 2020-12-14 18:31 UTC
I run a small self hosted, via the docker-zulip configuration, instance of Zulip for the company I work for. Two of my four users (who run Android) are reporting getting the attached screenshot on a group chat that includes them, and myself. I'm on iOS and have not had any issues. This began back in at least mid November, but I didn't realize the report wasn't just a one off glitch until recently. Or that it impacted both users.
![Screenshot_20201212-171618_Zulip](https://user-images.githubusercontent.com/1122990/102118689-4c3cb800-3dfd-11eb-8a52-f7c7aac6ee40.jpg)
Normally, I'd blame my server configuration, as that is usually the reason to have TLS errors, but the strange thing is that it *only* impacts this single group chat, other groups work properly, single PMs work properly, public streams work properly, and sometimes if they load a different group chat, and then switch back, the group chat works for a while. Additionally, everything works in browser (Chrome and Firefox on Windows 10, Firefox on Mac), and in my case the Zulip desktop app on Windows 10 and Mac.

Configuration details:
- Tracks docker-zulip:latest
- We do use a nginx reverse proxy to terminate TLS (as multiple vhosts are used), and the Zulip subdomain uses Let's Encrypt. Other subdomains do use self-signed certificates, as they are not available outside the firewall.
- Zulip itself uses self-signed configuration as I don't see any way to turn off HTTPS in the docs, but the only thing that sees that is the reverse proxy as the container port isn't directly forwarded.
- Duplicate HSTS headers are sent, as the proxy sends one, and passes on the other from Zulip
- https://www.ssllabs.com/ssltest/ otherwise gives an "A" rating.

Is there something I'm doing wrong in my configuration to impact only one group chat?

Edit: One of the users had an iPhone around, and he just confirmed that he does not see the issue in the app on that iPhone.

**Comment by gnprice** [comment] 2020-12-15 07:54
Thanks for the detailed report!

Because the app is successfully talking to the server otherwise, it seems like the issue can't be in the TLS certs the Zulip server (or rather its reverse proxy) provides.

One fact that's probably relevant is that when we show the actual message list for a given conversation, that's in a webview of its own. In your screenshot, the part of the screen that's blank and has that cert error centered in it is exactly the part that's provided by that webview. So it seems like the error is being shown by that webview. The browser for the webview is provided by the system Chrome on Android and Safari on iOS.

That doesn't by itself explain why that one conversation gives an error -- the URL for the webview is just a local `file:` URL, so no SSL/TLS there. (And if it *were* on the server, it'd naturally be on the same domain for all conversations.)

But, thinking about things that might be different in that one conversation: perhaps there's an image somewhere in that message history that's causing trouble? This could be a link someone shared which Zulip shows a preview for -- to an image anywhere, or a tweet, or a few other kinds of links that Zulip shows previews for. If there's an image which happens to be on a server whose TLS configuration isn't quite accepted by that device, then that could explain an error. (Though even then I'd have hoped that the browser would show the rest of the page and just show a "broken image" placeholder for that one image.)

Perhaps you can take a look through the history for any candidates for that problem. If this is happening when the user first opens that conversation after launching the app from scratch, before trying to scroll back through history, then it'll be somewhere in the latest 100 messages there. (Oh, rereading I see that sometimes it works for a while. Then maybe the trigger message is further back after all?) If we can find what triggers it, that'll help debug -- and it'll also give you a workaround, as you can delete that message.

As for why everything works for you on iOS, and in desktop browsers: my best guess is that whatever server has the problem is sending a cert that doesn't contain its full chain. That's historically the one thing that's caused recurring occasional reports of people having their Zulip server work fine for most browsers/devices but fail with TLS errors in others -- some discussion [in our docs here](https://zulip.readthedocs.io/en/latest/production/ssl-certificates.html#manual-install). (Here the Zulip server's own TLS seems to be fine, but of course the same thing may be affecting another kind of server.)

**Comment by alexferro** [comment] 2020-12-15 15:01
Well, I'm both happy and sad that it's probably not my server config. Happy, because I probably didn't make a mistake there while following the instructions, sad because it means it's something weirder to troubleshoot. 

One of my users actually suggested that same thought about a bad link (and we both thought that we'd hope the system web view was smarter than failing everything on a bad link), and I grabbed a full export (from the server console, not the web UI), in hopes of hacking a script to parse through the messages-*.json to extract all the web links to check them, but that failed due to my abysmal scripting skills. Are there better tools you have used for quickly searching through json to find things (like all the URLs linked, so I can pass them to a copy of curl known to fail on SSL errors) than just grep? Either way, I'll give that another shot.

It is very plausible that it's a link with bad https (from Android's perspective) in the chat history, as several of our internal servers don't have formally valid certificates (mostly from an internal CA, that these Android devices don't have loaded), and I'll try sending a couple of test messages via PM to one of the users containing links/images that Zulip will try to load, and see if it breaks that PM window the same way.

**Comment by alexferro** [comment] 2020-12-15 22:17
I have not found the message yet that is causing the problem, but I can confirm that sending a message with an image URL in it that goes to an HTTPS server that uses an untrusted root authority (internal corporate CA) breaks Zulip on Android, but not on iPhone. If you have a more private way to get an example link to you, I can send you the exact image URL I am testing with that is causing trouble, it's accessible to the internet, but I'd prefer not to immortalize it in a public issue comment. The only website I can find with bad ssl is badssl.com, which doesn't appear to have any images I can grab a link to for testing.

I don't know if any other invalid SSL configurations also can cause this, but this one certainly does. Also, my test user says he is running Android 9 (of some version) on a Galaxy S8+. I don't know what my other user is running.

I'll dig through the chat history and see if I can find a SSL error of some sort in the others and remove that, to at least fix our chat for now. I don't know if this is a bug that you have any control over, or one in an upstream component you bundle, or worse, in Android, but I think being able to poison a Zulip chat and/or stream by posting a link to an image is a bit of a bad thing.

**Comment by alexferro** [comment] 2020-12-15 23:15
Update: I think I have found the culprit in my chat logs and deleted them. Both users have confirmed the chat works after deleting a few messages.

At the time I sent the original messages, I mentioned a web site in a message that only existed for a few days, and Zulip automatically made the "infobox" message embed pane trying to show the contents of the website, and referencing a logo in the background image. A week later, I took down that page as the migration was completed, and suddenly it became a HTTPS error (that probably returns a 500 error inside it), as the certificate isn't valid anymore, and it's probably serving the default one, and then Android barfs on it. 
The exact culprit in my case, although the simple one of just posting an image link also causes the same problem, was this snippet from "rendered_content" in the message json.
```quote
<a class=\"message_embed_image\" href=\"http:\/\/URL_REDACTED.net\" style=\"background-image: url(https:\/\/URL_REDACED.net\/LOGO_PATH_REDACTED.png)\"><\/a>
```

Hopefully, this is enough information to help you track down any root causes in the system.

Thanks, Alex

**Comment by gnprice** [comment] 2020-12-16 06:03
Thanks for the debugging details, and I'm glad you were able to get things working again for you! I agree, this is a pretty nasty bug when it hits and so it'd be good to fix; though I also share your thought that it may be in some code we don't have much control over (potentially in the device's Chrome.)

If you'd like to share the exact URL that was in your repro, that'd be helpful too. You can send me a PM on chat.zulip.org, or send email to support@zulip.com and I'll see it there.

I actually went looking on badssl.com just yesterday as I was writing my reply here, and was disappointed not to find any images. :slightly_smiling_face: (Not on the actual "bad SSL" subdomains, anyway.) So having a precise repro to start from would be especially helpful, though we can probably figure it out from the details you've already provided.

**Comment by alexferro** [comment] 2020-12-16 06:37
I have just sent an email to support@zulip.com with examples of bad URLs hosted on our infrastructure. 

I took a closer look while writing that email, and one of the two URLs is actually nginx misconfiguration on my end that generates a http protocol error, versus serving a 500 error or similar with a self signed certificate, but both of them represent server behaviors (even if an unknown CA is a fairly common configuration in corporate systems) that cause a problem for the app.

**Comment by WesleyAC** [comment] 2021-06-21 22:01
This should be fixed in the most recent beta release — let us know if you see this problem after updating! (See #4726 for details)

**Closed by WesleyAC** 2021-06-21 22:01 UTC
Labels: a-Android, a-TLS, a-message list
