### ISSUE TITLE
Add support for reacting to a message that doesn't have any yet

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#303] opened 2017-02-10 03:09 UTC
We can do this via a longpress menu on a message.

**Comment by trueskawka** [comment] 2017-02-16 16:02
@zulipbot claim

**Comment by gnprice** [comment] 2018-05-24 00:56
There's a bit more discussion on #1304 , which was a dupe of this.

**Closed** 2018-07-28 07:42 UTC
Labels: in progress

**Comment by armaanahluwalia** [comment] 2018-08-03 12:13
@gnprice Is anyone currently working on this?

**Comment by agzuniverse** [comment] 2018-08-03 15:10
@armaanahluwalia this has been solved in #2775 , which has been merged into the master branch.
