### ISSUE TITLE
Keyboard pops up when following a push notification

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#2879] opened 2018-08-07 22:31 UTC
On my device (Samsung Galaxy S9+), after I click a push notification, it takes me the PM view with that user, and opens the keyboard ... but doesn't focus the text area.  So typing on the keyboard doesn't work.  

This has been annoying me a lot over the last few days, and I don't remember having noticed it before that; hard to tell whether this is because I was unable to sit at a keyboard yesterday or a regression.

Anyway, we should either not open the keyboard, or focus the compose area; I'd be tempted to not open the keyboard, since then there's more visual space to read the messages if there are more than one?  But either option is reasonable.

**Comment by borisyankov** [comment] 2018-08-13 20:51
@timabbott is this continuing to happen?

I did some testing and out of the 3 apps tested (FB Messenger, Skype, Viber) they all did the same - not have the keyboard focused, but also didn't pop it visible. It seems we should do the same.

In fact, this is what is happening on my phone (Samsung S8+) - the keyboard does not pop. @gnprice what happens on your phone?

**Comment by timabbott** [comment] 2018-08-13 21:05
Yes, this happens every time I click a push notification and try to reply.

**Comment by AmitJoki** [comment] 2018-08-14 00:25
@timabbott @borisyankov I am looking for a good first PR to get started contributing to this repo. This sounds interesting and not much of a work. Can you just give me a broad hint as to which files I've to be looked at? I'd be interested in solving this issue.

**Comment by borisyankov** [comment] 2018-08-14 19:11
@AmitJoki that might be a good first PR. I am not certain as the cause of the issue is unknown. Often that is how it goes.

The majority of the task will consist of trying to reliably reproduce the issue and finding other people that already have the issue.

Currently, we know:
 * it happens only sometimes
 * it happens on `Samsung Galaxy S9+` consistently (but not on Samsung Galaxy S8+ which is significant because of the software similarities)

It has something to do with custom Android keyboards, possibly the specific Android version, maybe a bug in React Native? 

What I would have done is some googling for this in general and searching the Issues section here
https://github.com/facebook/react-native/issues/

**Comment by AmitJoki** [comment] 2018-08-15 04:50
@borisyankov that's sad! It seems the error/anomaly is highly specific and irregular. And I don't happen to own Samsung Galaxy S9+, so there's no way to test.

I'd appreciate if you could point me to some other issues that could be a good first PR, as most of them are a work in progress or those which have been solved but just not closed yet.

**Comment by gnprice** [comment] 2018-08-15 05:51
Just tested on my Pixel 2 XL (with Android 8.1.0). Same behavior as Boris reported above:

> not have the keyboard focused, but also didn't pop it visible.

Which I agree seems like pretty reasonable behavior, and in fact that was Tim's preference in the OP so I guess we all agree on that. So this is a bug specific to certain phones, in particular Tim's Samsung Galaxy S9+.

@timabbott , what keyboard are you using? This should be in system settings; on stock Android 8 it's under System -> Languages & Input -> Virtual keyboard.

On that screen, if you touch the item for the keyboard you get its settings, which might have further details like a version. For each of two Google keyboards on my phone, the vertical-ellipsis "overflow menu" in the upper right has an "About" option which shows the exact version.

**Comment by timabbott** [comment] 2018-08-16 20:56
I have "Samsung Keyboard" as the default keyboard.

**Comment by borisyankov** [comment] 2018-08-16 21:29
That is weird. I have Samsung Keyboard 3.0.23.63
@timabbott could it be a bug related to an older keyboard version?

**Comment by timabbott** [comment] 2018-08-16 21:42
No idea; there doesn't seem to be a way for me to upgrade the keyboard version.

**Comment by gnprice** [comment] 2019-06-17 22:28
@timabbott , are you still seeing this on a current version?

I don't know of a specific change that would have fixed it; but it's been most of a year, so perhaps a change either we made, or RN, or your platform, has happened to fix it.

(BTW if anyone else experiences this issue, please comment! It'd be very interesting to hear how your device compares to Tim's, to help pin down the variables that trigger it.)

**Comment by timabbott** [comment] 2019-06-17 23:50
No, I'm not.

**Comment by gnprice** [comment] 2019-06-18 01:33
Good to know, thanks!

I'll close this as having been resolved mysteriously, then. As always, we can re-open or file a new issue if someone sees this symptom in the future.

**Closed by gnprice** 2019-06-18 01:33 UTC
Labels: area: Android, area: notifications, bug
