### ISSUE TITLE
Zulip Mobile Can send files Video and Preview Vdo  ?

### ISSUE THREAD

**Issue by wsupajirakit** [zulip/zulip-mobile#3541] opened 2019-07-01 12:56 UTC
Zulip Mobile Can send files Video and Preview Vdo  ?
How can i do that

**Comment by chrisbobbe** [comment] 2020-01-23 02:02
Closing as a duplicate of https://github.com/zulip/zulip-mobile/issues/2939.

**Closed by chrisbobbe** 2020-01-23 02:02 UTC
Labels: duplicate
