### ISSUE TITLE
New messages often don't load

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#1854] opened 2018-02-01 18:36 UTC
This morning I tried to catch up using the mobile app, 8.1.62 on Android. I basically couldn't, because in multiple streams and topics, either the new messages never loaded, or most of them didn't load. In each case, I was tapping on an item in the "Unreads" tab of the nav screen (the drawer, except in 8.1.62 it's not a drawer.)

Here's one where no messages loaded -- this was the usual case:
![](https://chat.zulip.org/user_uploads/2/cc/35d95T8qkLaCCI-DufLGCXih/Screenshot_20180201-085553.png)
We're doing the right thing here by showing the user that we're still trying to load these messages! But we should also actually load them. :-)

Here's one where just one message loaded, out of 6:
![](https://chat.zulip.org/user_uploads/2/d6/ZXqzDcLWJObMfZ7PJ86Z3YKr/Screenshot_20180201-090950.png)
(Or maybe out of 7? Definitely that one message was unread before I went to this screen.) In this case, we make the problem much worse by not showing any loading indicator. 

Just now, I went back and tried opening the same stream as my first example above; this time the whole stream, from the "Subscribed" tab, because there are no unreads left. Still nothing loads:
![](https://chat.zulip.org/user_uploads/2/fa/-e97szjoUKyYROajUK0U610B/Screenshot_20180201-102623.png)
This time, I waited over 15 seconds, on a fast wifi connection.

I saw this issue a lot yesterday too, and I heard other reports of it on 7.6.60. It makes the app pretty unusable, unfortunately, when it hits.

**Comment by gnprice** [comment] 2018-02-07 03:24
Since updating yesterday, I haven't seen this issue! (I'm on 8.3.64 now, but I think that might have been a further update and I was on ...63 then.)

So there could still be bugs that happen occasionally, but whatever was causing it to happen like half the time definitely seems to be fixed :). Closing this.

**Comment by gnprice** [comment] 2018-03-27 03:34
> I think I also saw the version of this issue where no messages show at all, and only the loading indicator; but I don't seem to have a screenshot of that

Aha, just saw this again now. Here's a screenshot -- I tapped on a stream from the unreads view:
![image](https://user-images.githubusercontent.com/28173/37945432-0cc270d4-3135-11e8-9c65-7f3f2ccf16f2.png)

**Comment by gnprice** [comment] 2018-04-02 20:31
Saw this again today, on version 81. This time it was combined with symptoms of #1545 or #2146 -- I landed far in the past, and then moreover scrolling down didn't work.

Specifically, I opened the `#test here` stream and landed on some messages from Feb 19, six weeks ago. There should be hundreds more messages to show, but it's as if these were the latest messages in the stream. Scrolling up into the past works normally; but if scroll back down, it stops at this spot again.

Screenshot:
![image](https://user-images.githubusercontent.com/28173/38214657-2ea7081e-367a-11e8-91c1-7a013fdb36af.png)

**Comment by armaanahluwalia** [comment] 2018-04-22 12:11
I just saw the same bug on the iOS app - version 10.1.70  
I posted a message using the web app and navigated to all messages in the mobile app. The new messages did not appear on the mobile app. When i closed ( shut down ) the zulip mobile app reopened and scrolled to the bottom of All Messages the new messages then appeared after a brief moment.

**Comment by borisyankov** [comment] 2018-05-09 14:29
Closing as fixed.

**Closed by borisyankov** 2018-05-09 14:29 UTC
Labels: bug

**Comment by lukasIO** [comment] 2018-08-25 13:05
I'm still seeing this behaviour occasionally on iOS, not sure about a specific pattern. but from the unread screen clicking on the stream name instead of the topic name seems to be the action that shows this behaviour the most. for me it's the behaviour that the new messages simply don't load. I see the old messages, but the new ones are not being loaded.
Version 16.2.96

**Comment by borisyankov** [comment] 2018-08-25 15:55
@lukasIO do they not load even if you scroll to the bottom and wait for a few seconds?

**Comment by lukasIO** [comment] 2018-08-25 18:32
Yes.
The expected behaviour I observe is, the messages load in chunks and I press the down arrow multiple times to get to the newest ones.
But in this case they simply don’t show, the workaround for me is to open the topic narrow instead of the stream, then the behaviour is as expected (loading dynamically in chunks). 
(Maybe this only applies to new topics, not sure)

**Comment by borisyankov** [comment] 2018-08-25 19:31
Thanks for reporting this @lukasIO 
It does not sound to be the same issue as this one so I did file this as a new issue #2918

This was currently not known. I will try to reproduce and fix.
